### ISSUE TITLE
What is the correct pattern for recv_all?

### ISSUE THREAD

**Issue by llimllib** [websocket-client/websocket-client#213]
Currently, I'm doing something like this to read data from the slack RTM api:

``` python
        data = []
        while True:
            try:
                data.append(self.websocket.recv())
            # SSLError in python < 2.7, SSLWantReadError in > 2.7
            except (SSLError, SSLWantReadError) as e:
                if e.errno == 2:
                    # errno 2 occurs when trying to read or write data, but more
                    # data needs to be received on the underlying TCP transport
                    # before the request can be fulfilled.
                    return data
                raise
```

Is that the correct pattern for reading all available data from a websocket?

**Comment by llimllib** [comment]
It seems that in wsdump you use `recv_frame` rather than `recv`, and switch on the opcode? https://github.com/liris/websocket-client/blob/master/bin/wsdump.py#L121

**Comment by liris** [comment]
At first, we were using only recv method. But after that, we need to handle opcode and some other stuff.

I recommend to use recv_frame to controll  more strictly.

**Comment by llimllib** [comment]
Would you be interested if I were to add a recv_all method? I don't want to know the details of the web sockets if I can avoid it.

**Comment by liris** [comment]
I think recv_all is dangerous because too bid data causes OutOfMemory error.
Only application takes care of this, not library.

**Comment by engn33r** [comment]
It looks like this code is working fine in [your slack.py](https://github.com/llimllib/limbo/blob/master/limbo/slack.py) file, but since this question was first asked, there are now [more code examples](https://websocket-client.readthedocs.io/en/latest/examples.html) and some [documentation about threading](https://websocket-client.readthedocs.io/en/latest/threading.html). I have not gotten around to documenting `create_connection()`, which is what you are using, but I plan to do so later. I didn't look too close at how you are using the websocket connection, but you might investigate whether the `WebSocketApp.run_forever()` function helps at all.
