### ISSUE TITLE
Curl like Authentication

### ISSUE THREAD

**Issue by cescoferraro** [websocket-client/websocket-client#218]
Is there any authentication method. My apps need a login to access the websocket endpoint. Are you guys thinking about it?

**Comment by liris** [comment]
we can set cookie or http header via "cookie" or "header" variables of connect method.

**Comment by nanohest** [comment]
In case anybody finds it useful.
This is a bit crude, but it works for me:
```
encoded_creds = base64.b64encode()'%s:%s' % (username,password))
ws = create_connection('wss://socket.example.com/',header=['Authorization: Basic %s' % encoded_creds])
```
I suppose it's something along those lines liris suggested.

**Comment by KohliDev** [comment]
Thanks for this suggestion. But one quick question we are just encoding the creds is it still secure to send them as part of the header, I don`t think it will go over encrypted communication channel.

**Comment by engn33r** [comment]
The WebSocket protocol as outlined in RFC 6455 does not have a built-in authentication mechanism. The authentication process is intended to be implemented by the developer, and therefore there are many different approaches to implementing authentication. Therefore, the only authentication currently built-in to this library at the current time is the "http_proxy_auth" parameter, to allow for authentication to a proxy. You will need to add some custom code to authenticate to the server you are attempting to connect to.

To answer @KohliDev's slightly off-topic question, using Basic Authentication can expose credentials to a man-in-the-middle party if you are using unencrypted communications, such as using HTTP instead of HTTPS. However, if the communications are encrypted, the credentials should not be exposed to a man-in-the-middle listener. Capturing traffic with a tool like Wireshark can help you confirm this.
