### ISSUE TITLE
Anaconda Packaging

### ISSUE THREAD

**Issue by mertzjames** [websocket-client/websocket-client#220]
I'd like to use this with the Anaconda distribution.  Submitting packages is pretty easy:

http://conda.pydata.org/docs/build_tutorials/pkgs.html

If you don't want to do this, then I'm willing to do it for you.  I just wanted to get your permission if so.

**Comment by liris** [comment]
Please work on this and send me PR.

**Comment by KronosKoderS** [comment]
Go ahead and assign this to me, and I'll get to work on it.

**Comment by engn33r** [comment]
It appears that the latest release created 2 days ago, 0.58.0, is [already available on anaconda](https://anaconda.org/anaconda/websocket-client). This was not due to any efforts on the part of this repository, but rather some external automated process. I suspect the [websocket-client conda-forge repo](https://github.com/conda-forge/websocket-client-feedstock) does this, but it doesn't look like that repository has been updated for 2 months. So while I'm not 100% clear about how anaconda got the latest websocket-client build automatically, this issue can be closed because the websocket-client library is available for installation from conda.
