### ISSUE TITLE
How to catch network failure immediately

### ISSUE THREAD

**Issue by jubyvictor** [websocket-client/websocket-client#245]
I have a use case where I should send data from a client over a cellular network once and only once. In order to do that I want to know how to handle a transient network failure in the best possible way. I have been trying to simulate a network fault by attenuating the cellular signal. I used setdefaulttimeout to 10 and ping_timeout and ping_interval to 10. However the ws.send method does not throw call on_error till ~ 120 seconds have elapsed. Is there anything that can be done to detect this early ?

**Comment by liris** [comment]
It depends on OS network configuration, I think.

**Comment by jubyvictor** [comment]
I tried mucking around with the sysctl params but did not see much difference. I suspect that the ping_timeout isn't being handled correctly in the code. What do you think of exposing a callback for on_ping_timeout ? If so I can submit a pull request.

 Right now I work around by maintaining 2 timestamps and have another thread monitor the delta between the TX timestamp and ACK timestamp and exit the web socket thread and restart it if the delta between the ACK and TX is greater than n seconds.

**Comment by engn33r** [comment]
The ping timeout code has been updated quite a bit since this issue was created. If the built-in ping/pong functionality is not working for your use case, a custom solution is probably the best approach. WebSockets do not have a built in means of message acknowledgement, so detecting a packet drop is not something normally done by the protocol.
