### ISSUE TITLE
Close frame handling bug

### ISSUE THREAD

**Issue by jbwdevries** [websocket-client/websocket-client#269]
In `recv_data_frame`, when an `OPCODE_CLOSE` frame is received, it always responds with a close frame. However, it should only do that when a `OPCODE_CLOSE` wasn't sent. In theory, if a server also has this bug, you could have an endless loop with close frames.

The specs also suggest to echo the close code back to the server. So I guess `send_frame` should store a close frame when sent, and in `recv_data_frame` it should check whether one exists. If so, it shouldn't send a new one. Otherwise, it should should send `frame.opcode` in the new close frame.

**Comment by engn33r** [comment]
Maybe the code around this has changed since this issue was first posted, but I don't see a problem with the current websocket-client connection close code. It sounds like there wasn't a working demo of the issue previously and it was mostly a concern if a server also had an implementation problem. I will outline my thoughts regarding the related functions in the _core.py file.

1. If the server initiates the closing process, the frame will be received by the `recv_data_frame()` function (which is called from `recv_data()`, which is called by `recv()`). The `recv_data_frame()` function will echo back a ABNF.OPCODE_CLOSE code when a server's close frame is received, set `self.connected = False`, and the `recv()` function will return an empty string.
2. If `websocket-client` initiates the closing process, the `close()` function is used. The `close()` function sends a frame with ABNF.OPCODE_CLOSE and does not call `recv_data_frame()` afterwards, but rather closes the socket.

Let me know if I missed something or if a scenario was found where this was an issue.
