### ISSUE TITLE
Shouldn't ABNF be public?

### ISSUE THREAD

**Issue by bkmeneguello** [websocket-client/websocket-client#300]
The "send" method (https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L109) uses ABNF.OPCODE_TEXT, but the OPCODE_BINARY requires that the websocket._abnf be imported.

**Comment by brannondorsey** [comment]
I also find myself wishing `ABNF` was public for this reason.

**Comment by liris** [comment]
I don't understand.
ABNF is public class. We can import like this


import ABNF from websocket

**Comment by bkmeneguello** [comment]
It is accessible, but not really public. It is in _abnf sub package, to be public it should be exported by main package.

**Comment by liris** [comment]
If sub package isn't public, what's the problem?

**Comment by bkmeneguello** [comment]
There is absolutely no problem, this issue is just a suggestion to make a better API

**Comment by engn33r** [comment]
I can see that making ABNF public may make things easier in some cases, but I will leave ABNF as it is for now since I think the current approach keeps things consist in this package. If you think I overlooked some benefits of making ABNF public or you feel strongly about this, please submit a PR with the fix and we can discuss it further.
