### ISSUE TITLE
Include the Server certificate on the request

### ISSUE THREAD

**Issue by npissan** [websocket-client/websocket-client#309]
Hi.
I am trying to connect on wss://   websocket using the websocket-client and the wsdump.py but the error is that 

> _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

I have tried to disable ssl cert verification but the server does not accept the request 
(the server has the same behavior as a browser that has not accepted server public cert)

Is there a way to insert the server public self signed certificate on the request?
something like

>  requests.get(url, verify=cafile)

Thanks

**Comment by engn33r** [comment]
There is a way to specify your own set of valid certificates using "WEBSOCKET_CLIENT_CA_BUNDLE" ([in the _http.py file](https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_http.py#L251)). You might find further information in #451, which I think discusses a similar topic. This issue is quite old and I think the latest codebase has some updates that may resolve it.
