### ISSUE TITLE
Fixed Source port?

### ISSUE THREAD

**Issue by juanp001** [websocket-client/websocket-client#321]
Hi i am creating a WebSocketApp instance 
ws = websocket.WebSocketApp("ws://apisocketsincloft.azurewebsites.net/api/GenericSocket",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
when I type ws.sock.sock i got this

<socket.socket fd=956, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.20', 50259), raddr=('13.94.47.87', 80)>

I would like to fix the port of laddr, how can i do that?

**Comment by liris** [comment]
Do you mean you want to use  wss? If so, you change url from ws:// to wss://

**Comment by alexvelickiy** [comment]
Same question. I mean to change port 50259 in example above.

**Comment by engn33r** [comment]
This issue appears to be asking about how to create a connection to an unusual port number. See the [project documentation examples page](https://websocket-client.readthedocs.io/en/latest/examples.html) for some example code that may help you. To specify a specific port number, just use "wss://example.com:50259" instead of "wss://example.com" as the connection destination.
