### ISSUE TITLE
Please consider follow the PEP8 code style

### ISSUE THREAD

**Issue by mckelvin** [websocket-client/websocket-client#348]
PEP8 is the official style guide for python code, please consider obey it. Also I'd suggest to enable a code linter (e.g.: `flake8` ) on https://travis-ci.org for this project. If it's enabled, PR with bugs like https://github.com/websocket-client/websocket-client/pull/347 will fail the CI pipeline.

**Comment by engn33r** [comment]
With the recent switch to GitHub Actions, an action now exists that does flake8 linting. However, because there's a lot of edits that are needed to make the code compliant with PEP8, the flake8 GitHub Action is currently enabled to always pass, so it won't be catching bugs right now. I will leave this issue open a bit longer until further progress is made on making the code more compliant to flake8. Volunteers are welcome for this effort!

**Comment by engn33r** [comment]
With commit dc3f5c4, the linting GitHub Action will run on any PR and trigger an exception in the CI process if PEP8 is not followed. Some non-crucial PEP8 test cases are currently optional in the action, but over time I hope we can close that gap.
