### ISSUE TITLE
There is no indication that a message frame is not complete

### ISSUE THREAD

**Issue by 13steinj** [websocket-client/websocket-client#351]
https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#Message_Fragmentation

This defines that there is a a finish flag sent with all messages, including completed ones. If the flag is 1, the message is complete, otherwise unfinished.

There is no way currently to define to the developer that a continuation message should be expected, leaving it up to the server via WebSocketApp. There is a second issue with WebSocketApp's implementation: It doesn't handle binary data. Though that should be a separate issue.

I propose that on_message gets an extra paramater defining the FIN flag, and that this be rewritten--

allowing for an on_binary function, an on_cont_binary, and changing on_message to on_text and on_cont_text, aliasing on_message and on_cont_message to these new new text functions, and finally, putting a deprecation warning on the use of on_message and on_cont_message. On a similar note, a deprecation warning should be put on using an old version of the on_close parameter

I'll gladly put in the work for the PRs if the proposal is fine.

**Comment by liris** [comment]
Please give me PR.

**Comment by engn33r** [comment]
Hey @13steinj, it's been quite a while since you posted, but if you are still considering writing a PR for this (or the binary data support), it would be greatly appreciated. However, it's also possible that upgrades have happened since you posted, since the [create_frame function](https://websocket-client.readthedocs.io/en/latest/abnf.html#websocket._abnf.ABNF.create_frame) has a way to set the FIN flag. As the new maintainer for the project and am trying to revamp a few things, so any input (even checking whether the create_frame function does the trick) would be helpful.

**Comment by engn33r** [comment]
The original issue highlighted two concerns:
1. The lack of continuation frame (opcode 0x00) support in the WebSocketApp class
2. The lack of binary frame (opcode 0x02) support in the WebSocketApp class

The solutions to these are "hidden" in comments of the _app.py file. The first concern should be possible to solve using the `on_cont_message` parameter of the WebSocketApp class, which is specifically for continuation frames. The second concern should be possible to solve using the `on_data` parameter, which return the data type (either ABNF.OPCODE_TEXT or ABNF.OPCODE_BINARY) as its third argument and a boolean indicating the continuation flag as its fourth argument.
