### ISSUE TITLE
No IPv6 SSL Compatibility

### ISSUE THREAD

**Issue by kevr** [websocket-client/websocket-client#357]
Hello. So there's a bug via SNI that this library causes when doing a handshake with the websocket server.

Natively, this library does not support IPv6 - it would be very nice if it did, since compatibility with this is increasingly important by the year, and this seems to be the only existing websocket library for python2 in the wild.

So, I've forced IPv6 by overriding the internal WebSocket().sock to use AF_INET6. I can connect to normal unencrypted ws:// addresses fine. The problem exists when using an IPv6 IP address to connect, say, `wss://[2001::2]/websocket` - Internally, your code sends over the wrong host (missing the brackets) in the SSL handshake. This is the same for the HTTP Host/Origin headers sent over during connect. With missing brackets, servers like apache see an SNI issue because they can not properly parse the IPv6 address without brackets.

I believe without this, the library will eventually become deprecated, and we will need a replacement that can support all types of network addresses.

Thanks for the interest.

**Comment by liris** [comment]
we need support "CONNECT"  for proxy.

Is it enough to support IPv6? Otherwise, please send me PR.

**Comment by kevr** [comment]
I'll work on this in my off time, thanks for being open to PRs!

**Comment by engn33r** [comment]
There are other issues relating to IPv6 problems which indicate this may still be a problem point in the library, but I do not have any quick means of testing and verifying this myself. I will close this for now since I can neither confirm nor deny the issue, but if it reoccurs in the latest version of the code, I will take that as sufficient evidence to look into this further. Probably some 

If someone reading this has encountered this issue in the future (or can confirm that IPv6 is, in fact, supported by this library), it would be great to see additional information as described in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) or a public IPv6 URL/IP websocket endpoint that demonstrates this issue.
