### ISSUE TITLE
AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

### ISSUE THREAD

**Issue by navxio** [websocket-client/websocket-client#374]
Trying to run the javascript websocket like api example I come across this error

Traceback (most recent call last):
  File "socket.py", line 1, in <module>
    import websocket
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/_app.py", line 35, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/_core.py", line 33, in <module>
    from ._handshake import *
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/_handshake.py", line 30, in <module>
    from ._http import *
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/_http.py", line 31, in <module>
    from ._socket import*
  File "/home/nav/.Virtualenvs/gplay/lib/python3.6/site-packages/websocket/_socket.py", line 27, in <module>
    from ._ssl_compat import *

**Comment by navdeepio** [comment]
@liris yes

**Comment by liris** [comment]
What kidn of exception did you get?

**Comment by navdeepio** [comment]
no exception, it worked fine

**Comment by evanlwj** [comment]
Same issue happened to me, suspected "if hasattr(ssl, 'SSLContext') and hasattr(ssl.SSLContext, 'check_hostname'):" in _ssl_compat.py, but it actually worked when I ran manually from Python console

Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> hasattr(ssl, 'SSLContext')
True
>>> hasattr(ssl.SSLContext, 'check_hostname')
True

**Comment by evanlwj** [comment]
I fixed this issue, it's an environment configuration issue to me. 

Please let me give more context here, this error happened in starting debugging in Visual Studio Code in Windows 10, Python 3.7 was installed with [Anaconda](https://www.anaconda.com/), however I also have WSL with Python 3.7 as well, Visual Studio Code launched from WSL command prompt, but I thought it still read environment configuration from Windows instead of WSL. then it missed the proper configuration in WSL. After I set up proper configuration to Windows one(Anaconda command prompt), and Visual Studio Code got launched from Anaconda command prompt), issue was gone. Thanks

**Comment by ROhhBee** [comment]
@evanlwj can you explain how you fixed the environment configuration issue? I am having this exact problem but I cannot seem to find a solution.  For me it also works fine in the Python Console but I get that error when I run the program. I am not familiar with how to make the changes to the virtual environment.  Further details would be appreciated.

**Comment by lafada** [comment]
Solution for Mac ?

**Comment by engn33r** [comment]
This issue should be resolved by adding `import ssl` to the top of your Python file. I have encountered this issue as well when I forget to add this line.
