### ISSUE TITLE
WebSocketApp._callback catches all exceptions

### ISSUE THREAD

**Issue by peixinchen** [websocket-client/websocket-client#377]
In my opinion, it's a bad practice. It took me a day to figure out a spell error. Should on_error callback be called in some error happen?

**Comment by tristan-fairbairn** [comment]
I came here to report the same thing, +1

**Comment by fboender** [comment]
For those running into the same problem, you can monkey patch the ws._callback method so it calls the on_error handler and then simply raise the first param of the `on_error` handler:

    def monkey_callback(callback, *args):
        """
        Monkey patch for WebSocketApp._callback() because it swallows
        exceptions.
        """
        if callback is not None:
            callback(ws, *args)
    
    def ws_on_open(ws):
        pass
    
    def ws_on_message(ws, message):
        pass
    
    def ws_on_error(ws, error):
        raise error
    
    if __name__ == "__main__":
        ws = websocket.WebSocketApp(
            url,
            on_open=ws_on_open,
            on_message=ws_on_message,
            on_error=ws_on_error
        )
        # Monkeypatch WebSocketApp because it swallows exceptions.
        ws._callback = monkey_callback
        ws.run_forever()

**Comment by BenBao93** [comment]
@fboender that works, very helpful. It is really annoying that we can't get the errors straight away, would have taken me hours to fix if I wouldn't have found this!

**Comment by GliderGeek** [comment]
@fboender: thanks a lot for the solution. It cost me quite some time to find that this was the source of my problems. It would be very much appreciated if this is changed/fixed.

**Comment by mujina93** [comment]
Nice solution. Do you know if there is some option to switch from "swallow all exceptions mode" to "raise exceptions mode" and vice versa?
If there is none, maybe it's worth to make a pull request with that, so that we have the monkey-patched version as the default option.

**Comment by engn33r** [comment]
I reopened this after 708 mentioned what appears to be a duplicate concern. To rephrase what was said before, `on_error()` is not called unless the monkey patch from @fboender is used. I will update the FAQ and other locations where `on_error()` is mentioned to include this monkey patch. I am open to a PR that implements this with minimal impact to other use cases.

Below is the sample code I used to test this behavior.

```python
import websocket

def monkey_callback(callback, *args):
    """
    Monkey patch for WebSocketApp._callback() because it swallows
    exceptions.
    """
    if callback is not None:
        callback(wsapp, *args)

def on_message(wsapp, message):
    print(message)
    raise TypeError("Where is my exception")

def on_error(wsapp, err):
    print(err)

wsapp = websocket.WebSocketApp("wss://stream.meetup.com/2/rsvps", on_message=on_message, on_error=on_error)
wsapp._callback = monkey_callback # Removing this removes the exception
wsapp.run_forever()
```

**Comment by EddieBreeg** [comment]
This solution indeed allows you to catch errors unfortunately it completely stops the application (or at least it did in my case).
What I did to overcome this is to handle the exception directly in the monkey_callback function:
```python
app = websocket.WebSocketApp(url)
def _callback(cb, *args):
	if cb is not None:
		try:
			cb(app, *args)
		except Exception as err:
			print(err)
app._callback = _callback
```

**Comment by engn33r** [comment]
@EddieBreeg thanks for posting an improved version. The `_callback()` function at the end of the _app.py file has similar exception handling to what you shared. If other users want to more closely mimic the behavior of _app.py, you could probably copy the exception clause from `_callback()` in _app.py.

Has anyone in this thread still encountered the issue when the line `websocket.enableTrace(True)` is included in your code? It occurred to me that the `if _logging.isEnabledForDebug():` block in the _app.py `_callback()` exception clause might require this to print the traceback.

**Comment by EddieBreeg** [comment]
Having tracebackEnabled set to True does indeed solve this issue but it will also print out a lot of extra information about the websocket message headers that will clutter your terminal a lot. Since I was only interested in Python errors, and there is seemingly no way to enable debug alone (if there is please tell me I'd love to know) this monkey patch kind of is the way to go for me.

**Comment by engn33r** [comment]
@EddieBreeg Ok, I see your point that the other trace messages aren't needed, but at least the logic for providing the info you're looking for is there. I'll consider changes to the callback exception handling (PRs welcome). Perhaps simply removing the `if _logging.isEnabledForDebug():` line would work. It does seem odd to me that this one edge case doesn't provide the verbose exception details that other errors do.

**Comment by EddieBreeg** [comment]
Removing the if statement does indeed completely solve the problem! What would be best in my opinion would be to make functions available to enable logging on the debug level, similarly to what the enableTrace function does. That would allow the user to control what it is they want to print to the console. I'm guessing the appropriate logging level would be logging.ERROR although I am not certain it is the case

**Comment by engn33r** [comment]
I agree that an `enableDebug()` function, similar to `enableTrace()`, would be nice. But would `enableDebug()` serve a purpose anywhere else in the code other than this single location? I've thought about such a function too but I think all other exceptions in websocket-client generate a verbose trace other than this instance, so a solution to this one callback exception might be all that's needed. Or at least I assumed this was the only location that had unexpected behavior because this type of problem has only been mentioned around the callback exception.

I will further add that before making larger changes to websocket-client logging, if we go with the 'enableDebug()' route in the future, I would want to get input from someone using a logging tool like sentry to understand if there's specific logging improvements we can make for tools in larger scale production environments

**Comment by EddieBreeg** [comment]
I think I found a solution that could give us the best of both worlds: in the if block of the _callback method (that we could actually remove I suppose) instead of simply printing the exception, we can check if the on_error callback has been defined by the user.
In which case we simply have to call it.
```python
if _logging.isEnabledForError() and self.on_error:
        self.on_error(self, e)
```
That way we don't have to create a specific function that would indeed only be used in this specific usecase, but the user still gets to decide whether or not they want to do something with the exception. Even better: they get to decide exactly what they'll do with it, since this solution essentially makes sure on_error will always be called (assuming it exists).

**Comment by engn33r** [comment]
Nice, that's a clever solution. Do you want to submit a PR for this? I can make the change if you don't want to.

**Comment by EddieBreeg** [comment]
Yeah I'm going to submit a PR?

**Comment by gister9000** [comment]
If you want the stack trace and not just the error message, do this

```
import websocket
import traceback


def ws_on_open(ws):
    print('connected')

def ws_on_message(ws, message):
    print(message)
    raise Exception('test')

def ws_on_error(ws, error):
    print(error)
    traceback.print_exception(error)

if __name__ == "__main__":
    ws = websocket.WebSocketApp(
        "wss://stream.meetup.com/2/rsvps",
        on_open=ws_on_open,
        on_message=ws_on_message,
        on_error=ws_on_error
    )
    ws.run_forever()
```
