### ISSUE TITLE
select not returning readable when websocket pkt is waiting

### ISSUE THREAD

**Issue by element-82** [websocket-client/websocket-client#420]
This is a strange issue, where we are relaying over a websocket to a local service.  However, the select on the websocket is not returning readable. E.g.:
```
while True:
     socket_list = [self.wsock]
    read_sockets, write_sockets, _es = select.select(socket_list,
                                                 [], [], select_timeout)
    for sock in read_sockets:
       code here
```
In this case, I am waiting for an ssh pkt to show up, but read_sockets is always zero.  However, the pkt is there when I force it  before the for sock in read_sockets loop after a count.
```
read_sockets.append(self.wsock
```

See the code here:
https://github.com/Wind-River/device-cloud-python/blob/relay_fixes/device_cloud/relay.py

**Comment by engn33r** [comment]
It looks like the links you've provided might be for a discontinued product. If this is still a relevant issue, please share more about it using the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) so I can better understand where the issue is and if it is in the websocket-client code. This looks like an issue that is likely outside the scope of this library.
