### ISSUE TITLE
[Question] Any guarantees on thread-safety?

### ISSUE THREAD

**Issue by shdown** [websocket-client/websocket-client#431]
Does `websocket-client` provide any guarantess on the thread-safety of any operations?

Specifically, I need to call the `close()` method of `WebSocketApp` object from the thread other than that it is running in. It is safe, and what should I do instead if it is not?

**Comment by kylejmcintyre** [comment]
I am similarly curious if there's issues with on thread receiving, while another sends. I'm seeing issues where messages from my server aren't making it to the client and theorize it happens when another thread writes.

**Comment by engn33r** [comment]
No, thread-safety is not very well documented for this project and there are no guarantees other than those provided by the thread-related Python libraries (specifically [threading](https://docs.python.org/3/library/threading.html)) that you use. You can review [the project documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) on this subject and review the source code and past issues for further details. Since you specifically mention the `close()` function, you may want to look at issue #612.
