### ISSUE TITLE
Add PAC (proxy auto-config) support

### ISSUE THREAD

**Issue by Ro-Den** [websocket-client/websocket-client#458]
Is it possible to add PAC ( https://en.wikipedia.org/wiki/Proxy_auto-config ) support?

A couple of Python projects relevant to the issue:

- PyPAC: http://pypac.readthedocs.io/en/latest/
- Pacparser: http://pacparser.manugarg.com/

**Comment by engn33r** [comment]
I would be happy to review a PR if someone would like to implement this feature, but I do not think there is sufficient interest for me to prioritize this feature at the moment given this project's other priorities. I will close this issue for now because I do not view it as a priority.

If others would find this feature valuable, please leave a comment here or upvote the original request so I can properly gauge interest.
