### ISSUE TITLE
WebsocketApp does not identify callback arguments correctly on 0.49.0

### ISSUE THREAD

**Issue by SparkyTheAlbino** [websocket-client/websocket-client#463]
Using:
Python Version: Python 3.4.2
OS: Raspian Lite (Raspberry Pi Model 3B+)

When using the latest version 0.49.0 on_open, on_error, on_close all cannot see the args and therefore breaks everything and not connecting at all.

Downgrading back to 0.48.0 works fine, have been running this on another raspberry pi for quite some time now. Downgraded this new Raspberry pi to 0.48.0 and its working fine.

```
08/16/2018 12:58:26 PM -      ERROR: error from callback <bound method Operator.on_cxn_open of <__main__.Operator object at 0x7640b8f0>>: on_cxn_open() missing 1 required positional argument: 'ws'
  File "/usr/local/lib/python3.4/dist-packages/websocket/_app.py", line 329, in _callback
    callback(*args)
```

Here are few snippets from my code that may help:
```
self.ws = websocket.WebSocketApp(host + self.ID,
                                on_open    = self.on_cxn_open,
                                on_message = self.on_message,
                                on_error   = self.on_cxn_error,
                                on_close   = self.on_cxn_close,
                                header     = headers
                                )

    def on_cxn_open(self, ws):
        self.connected = True
        logging.info(self.ID + "---- connection opened")
        return
```

**Comment by swedishmike** [comment]
@SparkyTheAlbino 

I'm experiencing the same issue trying to use the certsteram library and I originally opened this issue, https://github.com/CaliDog/certstream-python/issues/18, there since I thought the problem might lie in that end. 

However, your issue seems to be very similar and downgrading to 0.48.0 sorts it for me as well. I saw that @nlevitt opened this pull request, https://github.com/websocket-client/websocket-client/pull/462, which sounds like it  might address this issue. I tried to appy it manually and re-installed the websocket library but it didn't solve it in my end.

Have you tried that fix yet?

**Comment by swedishmike** [comment]
I just tried with the newly pushed version 0.5.0 and certstream and the problem persists there. @SparkyTheAlbino - does that version make any difference in your end?

**Comment by nlevitt** [comment]
certstream subclasses WebSocketApp. It appears that #442 was intentionally a breaking change for this use case. 

In other words, it looks to me like certstream needs to migrate to the new api or pin to websocket-client<=48.0, unless @liris and @bashlakov change their mind about #442.

```
class CertStreamClient(WebSocketApp):
    ...
    def _on_open(self, instance):
        ...
```

**Comment by liris** [comment]
I’m thinking it is better to revert these changes because of breaking the compatibility.

**Comment by liris** [comment]
ae589495b75162703ab4fe1f8712f50d22b12d4e

revert #442
