### ISSUE TITLE
Support for HTTP Authentication

### ISSUE THREAD

**Issue by verybadsoldier** [websocket-client/websocket-client#470]
Is there any way to use this package to connect to a websocket server that requires HTTP authentication like BasicAuth or Digest?
I could not find anything in the code about it nor in the issue tracker. I could not find proxy authentication.
Am I right that this is currently not supported? I can stop searching then :)
It would we really nice if the package could support it. Maybe I can volunteer to add it?

**Comment by liris** [comment]
Proxy authentication is not supported, currently.
If you need HTTP authentication, please set it to http header. We have a option to set it.

**Comment by wom-bat** [comment]
Setting a header works for basic auth, but not for Digest auth.

**Comment by YanzhongSu** [comment]
Hi, can you provide a code snippet that provides auth header? For example, given below code, where should I put the proxy auth header?
```
import websocket
ws = websocket.WebSocket()
ws.connect("ws://example.com/websocket", http_proxy_host="proxy_host_name", http_proxy_port=3128)
```

**Comment by verybadsoldier** [comment]
An incomplete example but you will get the idea:
```python
    def _build_auth_header(credentials: Tuple[str, str]) -> str:
        auth_str = f'{credentials[0]}:{credentials[1]}'.encode('utf-8')
        base64_auth = base64.b64encode(auth_str).decode('utf-8')
        return f'Basic {base64_auth}'

    def connect(self) -> None:
        _logger.info(f"Connecting to URL: {self._url}")
        self._websocket = websocket.WebSocket()

        header = {}
        if self._credentials is not None:
            header['Authorization'] = _build_auth_header(self._credentials)

        self._websocket.connect(self._url, http_no_proxy=['localhost'], header=header)
```

**Comment by engn33r** [comment]
@verybadsoldier if you are still interested in making a PR for this functionality, it would certainly be welcomed as a great addition!

I will close this now because the [project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html?highlight=proxy#connecting-through-a-proxy) outlines what is currently supported for connecting with proxies (namely the `http_proxy_auth` parameter) and other implementation-specific authentication must currently be added with custom headers or similar solutions.
