### ISSUE TITLE
Connecting Hivemq broker over web socket  timeout issue.

### ISSUE THREAD

**Issue by santosh-samal** [websocket-client/websocket-client#483]
Hi , 

I am trying to communicate with hivemq mqtt broker over web sockets. I could able to connect and publish and subscribe hardly 2/3 messages . after that the connection disconnects.

What could be the reason. Does HiveMQ broker has any restriction over web sockets ? or its the websocket having the problem ?

I am using websocket over proxy using HttpConnectProxy.

Thanks,
Santosh Samal

**Comment by liris** [comment]
At least, we need log to to figure out what is happening.

**Comment by engn33r** [comment]
If this issue is still a problem, please share additional information as described in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). Unfortunately I cannot provide an answer with the limited information you shared.
