### ISSUE TITLE
WebSocket4Net websocket timeout after 60 seconds !

### ISSUE THREAD

**Issue by santosh-samal** [websocket-client/websocket-client#484]
I am using WebSocket4Net websocket to communicate over mqtt. But websocket closes after 60 seconds.Is there any way to increase that time out.

Thanks,
santosh

**Comment by liris** [comment]
Timeout depends on the server. Client doesn’t handle it if the connection doesn’t have any problems

**Comment by engn33r** [comment]
As part of the ongoing effort to reduce the number of stale/duplicate issues, I am closing this issue due to the lack of detail around the circumstances of this issue. As liris mentioned previously, it sounds like this issue may have existed on the server side of the connection, not on the client side. If you are still encountering this issue, you can reopen this issue and provide additional details.
