### ISSUE TITLE
How to determine if there is another completely received message?

### ISSUE THREAD

**Issue by jbrekelmans** [websocket-client/websocket-client#505]
I am building a real time application where acting on an incoming message is bad if a successive message (with more up-to-date information) has already been received. This may happen in the event of server hiccups. I can protect against such a scenario by checking whether another message is buffered, but there does not seem to be an API for this.

Please advise whether or not it is possible to determine from `WebSocketApp.on_message` if another buffered message will immediately follow.

**Comment by engn33r** [comment]
As far as I understand, this is something that you should handle in your custom implementation, rather than something built-in to the library. WebSockets do not have any sequence number (see related issue #364), and therefore these is no inherent ordering of messages. If your WebSocket client needs to handle messages differently is multiple messages are received in a short timeframe, or under certain conditions, then it is up to you to customize this behavior. If you are specifically asking about the buffer, issue #622 is on a related topic. You may find [the project FAQ](https://websocket-client.readthedocs.io/en/latest/examples.html) helpful, which is new since this question was originally asked.
