### ISSUE TITLE
close() function does not work as expected when ping_interval parameter passed into run_forever

### ISSUE THREAD

**Issue by machinestar** [websocket-client/websocket-client#508]
Found that if I pass ping_interval parameter into run_forever() for websocket, close() function won't work. In my case, I have to include this parameter to keep connection alive.  Is this an expected behavior? Any insight would be appreciated. 

`

    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("ws://echo.websocket.org/",
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close
                                )
    ws.on_open = on_open
    wst = threading.Thread(target=ws.run_forever(ping_interval=2))
    wst.daemon = True
    wst.start()
    time.sleep(5)
    ws.close()
    print('done')
`

**Comment by Nisces** [comment]
Because target=ws.run_forever(ping_interval=2）means to call run_forever(ping_interval=2) function and pass the return value to the parameter target. However, run_forever would not stop and would not return any value

**Comment by tadly** [comment]
I have the same issue. A workaround for now is to:
`ws.sock.abort()`

[You skip a lot of `close` logic though](https://github.com/websocket-client/websocket-client/blob/9c73ddfbeb00fac9aa19c856d0b3b225a444dfc1/websocket/_core.py#L393-L432) so I'm not sure how good of an idea this actually is.

Because I do this only on program exit **and** my websocket server reports proper client disconnects, I don't care all that much.

**Comment by engn33r** [comment]
I haven't gotten to the root of this issue yet, but I suspect part of the issue here is [this if statement](https://github.com/websocket-client/websocket-client/blob/edb95d897f8f0b5d22406a9b264d2678ff350499/websocket/_app.py#L290), which sets `enable_multithread=True` if you are using ping_interval. The [threading documentation for this project](https://websocket-client.readthedocs.io/en/latest/threading.html) is still in the works at the time of writing, but I would suggest looking into what enable_multithread does and other past issues with this variable. I think issue #612 is getting close to an answer, possibly related to `from threading import Thread`, as two different code examples are pointed out with this where the problem does not exist.

**Comment by engn33r** [comment]
I think this is more similar to issue 612 than I first thought. The [threading documentation](echoapp_client.py) has been updated with an example (similar to the /examples/echoapp_client.py code) that should provide a solution to this approach. If you still encounter issues, please provide your updated code with more details and I can reopen the issue.
