### ISSUE TITLE
IPv6 unreachable addresses give failed connections

### ISSUE THREAD

**Issue by gerph** [websocket-client/websocket-client#522]
I'm trying to fetch data from "ws://live.lightningmaps.org/". This resolves to IPv6 addresses:

```
> host live.lightningmaps.org
live.lightningmaps.org is an alias for s5.ws.lightningmaps.org.
s5.ws.lightningmaps.org has address 91.121.41.140
s5.ws.lightningmaps.org has IPv6 address 2001:41d0:1000:468::2
```

The code in websocket correctly tries to step through these addresses, but then fails to connect to the IPv6 one with a 'Network unreachable' error - because my ISP, in its wisdom, provides a router that assigns a local IPv6 address but then fails to actually establish an upstream route for it (actually, that's pretty reasonable behaviour, but they only just stopped providing a route in the last day or so).

There's a simple fix for this that appears to work for me - update the connection code in _http.py to have something like:

```
            if error.errno in (errno.ENETUNREACH, ):
                err = error
                continue
```

and such failed connections will be treated like the host was not listening, and cause the connection code to move on to the next address. This has worked for me, in any case.

**Comment by engn33r** [comment]
I cannot replicate your issue because I'm not seeing any IPv6 address. Here's what I see:
```
> host live.lightningmaps.org
live.lightningmaps.org is an alias for s1.ws.lightningmaps.org.
s1.ws.lightningmaps.org has address 195.201.172.16
```
And I can run the following code without any errors:
```
import websocket

websocket.enableTrace(True)
ws = websocket.WebSocket()
ws.connect("ws://live.lightningmaps.org")
ws.send("Hello, Server")
print(ws.recv())
ws.close()
```

If you are still able to replicate this issue with the latest 0.58.0 release and Python 3, then please share some more info along the lines of what is in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). Until then, I will close the issue, but will reopen if more details are provided.

**Comment by gerph** [comment]
Huh, I guess they must have removed the IPv6 host adderss from it - it was there but isn't now, and I don't have another reference site that uses IPv6. So, no worries :-D
