### ISSUE TITLE
what to do if when I use ws.recv, but it never returns any value forever? How can I detect the connection is lost and reconnect? Thanks.

### ISSUE THREAD

**Issue by zhuyw05** [websocket-client/websocket-client#523]
Is there a is_connected function provided? Thanks

**Comment by 18969927785** [comment]
I have the same problem, do you solve it now?

**Comment by dayongi** [comment]
use 'while True' maybe can slove your problem , this is easy way

**Comment by engn33r** [comment]
Based on the title of this issue, I am guessing that you are using code that looks like:
```
ws = websocket.WebSocket()
ws.connect("ws://echo.websocket.org")
ws.send("Hello, Server")
print(ws.recv())
```
The WebSocket class is designed for shorter-lived connections. If you are waiting to receive a response, you may want to use the WebSocketApp class `run_forever()` function, which is better for a longer-lived connection because it remains running (and listening) as long as the connection is alive. The [examples documentation page](https://websocket-client.readthedocs.io/en/latest/examples.html) provides examples for both situations, as does the README.md file.
