### ISSUE TITLE
Legitimacy of license change

### ISSUE THREAD

**Issue by jugglinmike** [websocket-client/websocket-client#526]
[On 2018-10-27, the license for this project was changed from the LGPL to the BSD license.](https://github.com/websocket-client/websocket-client/commit/e94ed9e078c7772a7dc0a115da1a34c493f290b6) Since this project does not maintain a CLA, contributors own their own changes, so a change like this can't be made without their approval. Neither the above commit nor [the corresponding release notes](https://github.com/websocket-client/websocket-client/commit/1ac65e34bece850932250acbdffecf26f62f3d74) make mention of this, so I'm wondering if this project can actually be published under the BSD license.

**Comment by jugglinmike** [comment]
@liris Can you comment on that change?

**Comment by liris** [comment]
What should I do for this?

**Comment by jugglinmike** [comment]
It depends on if you have the consent of the prior contributors. If they've all agreed to have their work re-licensed, then it's fine to change to the BSD license--no action required. If they haven't all agreed, then commit e94ed9e078c7772a7dc0a115da1a34c493f290b6 should be reverted.

**Comment by asafkahlon** [comment]
In addition, it seems like the source files still specify the LGPL-2.1+ license format, although the main license file is BSD.
I guess the source files should be updated too...

**Comment by jellelicht** [comment]
Does this mean we can consider any release after ~0.54 to be made available under the lgpl-2.1+, or rather the bsd license?

**Comment by penrods** [comment]
@liris, switching licenses is a little tricky.  I see you have personally submitted the vast majority of the work on this project (thank you!), but you also *have* allowed others to also contribute to this project.  At the time they contributed code it was under a certain set of rules and assumptions (i.e. that the project was running LGPL).  If you want to change that, you need to either get their permission/agreement or you need to remove their code contribution.

Doing this "right" is tricky, but possible.  I also think it is worth it.  I converted Mycorft from GPLv3 to Apache 2.0 (plus a Contributors License Agreement, or CLA).  Github doesn't have any built-in mechanism for performing actions such as these, but here is what I did:  https://github.com/MycroftAI/mycroft-core/issues/927

I'd recommend doing something similar.  Grab names from the Github contributor list (https://github.com/websocket-client/websocket-client/graphs/contributors) and tag everyone who was involved in an Issue.  Ideally you'd get active consent from all of them in that Issue and can cross them off (since you don't have a CLA, this is probably the simplest way).  If anyone objects you either have to remain with the original license or you can remove their code.  With Mycroft I got signoff from the vast majority of contributors, push back from one individual and I removed their contribution (which was fortunately small) to resolve that.  A handful never responded after several attempts to contact them, so I believe it was legal and ethical to consider their lack of response as consent.

This is a bit of a hassle and I know nobody like doing this kind of stuff.  But it is important to do things right to honor everyone's involvement in open source projects.  Hopefully my comments and example helps, I'm happy to give my opinion if you have further questions.

P.S.  I'd asked about license changes back in this issue: https://github.com/websocket-client/websocket-client/issues/333, where you had moved to LGPLv3.  I'm personally very happy with the BSD license and would consider getting the license cleanly nailed down once and for all a great boon to your project.

**Comment by jugglinmike** [comment]
I wouldn't assume the support of non-respondents--contributions like that really ought to be re-written.

Here's another example http://mikepennisi.com/blog/2020/you-may-finally-use-jshint-for-evil/

**Comment by penrods** [comment]
@jugglinmike, I agree that ignoring a non-response is definitely something to not take lightly.  In Mycroft I did this as early as possible before our contributor list blew up and broadcast it widely (https://mycroft.ai/blog/right-license/) and fortunately the vast-vast majority of the code contributors responded positively.  I removed the small amount of code in a batch file from one contributor who objected.  The few non-responding individuals had contributed what the JSHint writeup referred to as "non-substantive" -- fixing comments, typos, pep8 complaints, etc.  In JSHint's case they faced the worse scenario -- a significant contributor who didn't respond -- and they had to decide what to do from there.

Worrying about the multitude of scenarios is probably not productive.  I think a maintainer should just cross their fingers try.  This project only has 98 code contributors, and a large portion of those are single-commit (single line) changes.  I'd still try to @ everyone in that list first, then check off those who respond positively to the change.  Then really start examining the non-responders.

P.S.  The project might consider a Contributor License Agreement (CLA) to centralize decisions like these.  However many people have reservations about CLAs (which I do understand, although I generally am OK with them personally).  This is difficult to implement once a project is in the wild, but if the relicensing is contacting everyone anyway it might be worth asking nicely if that would be possible.  But I wouldn't push for the CLA since it can be polarizing -- the request should be worded very carefully to make clear that implementing a CLA is not directly tied to the permission to change the license.

**Comment by engn33r** [comment]
Hi everyone, I wanted to mention that as the new maintainer of this project, this issue is on my radar. Special thanks to @penrods for being so persistent on this topic in past issues! I agree that there's been quite a number of license changes and I wasn't using this library when that all happened, so I'd like to ask a few questions to try and resolve this:
1. What's the easiest path forward? Is there a certain license that's easier to transition to, or a certain process that's less effort than others? Does having the current maintainer's active help make things easier at all? :smile: 
2. How do we handle contributors who are unresponsive to any license change queries?
3. Does anyone want to help take on this process, either by creating a checklist of what needs to happen or creating a new "Projects" item in this repository? Sounds like it's mostly just reaching out to all contributors, but if anyone wants to offer specific steps, we can set those in motion.

And has anyone personally experienced issues with this project's licensing in their usage of it? If not, perhaps this isn't a high priority concern at the moment, but I would like to get this resolved at some point.

**Comment by jellelicht** [comment]
@engn33r not directly helpful, but I do think the most immediate issue is that the license listed currently is simply not correct, as the initial license change was not handled correctly. 

The solution to this issue is to simply present the aggregate package as being licensed under lgpl2.1+. I think the license file (and GH page) should reflect this, as the current information is factually incorrect and potentially misleading.

Transitioning to having the package _also_ be available under a different license (and retroactively legitimising the borked licensing change) is an (IMHO) less pressing issue.

**Comment by engn33r** [comment]
@jellelicht Thanks for the input. I looked at this a bit closer and just want to double check that I understand the history and reasoning to reach the proper conclusion:
1. Jan 6 2011: Commit c2eec58 uses the LGPL v2.1 as the original license when the project was created
2.  Dec 2 2016: Commit 6c666c8 changed the license to LGPL 3. This license change was probably due to a misunderstanding of #282. This license change was allowed per the [LGPL relicensing FAQ](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). This spawned issue #333
3. Dec 24 2017: Commit ec1d926 changed the license back to LGPL 2.1. This license change was also allowed per the previously mentioned LGPL relicensing FAQ
4. Oct 28 2018: Commit e94ed9e moved this project to the BSD license. This change was NOT valid. This issue, #526, is a result of this change.

My conclusion is that the easiest path forward is to change this project back to the LGPL v2.1 license and the license issue should be resolved. Is this conclusion accurate? If so, I'll review the [GNU how-to](https://www.gnu.org/licenses/gpl-howto.en.html) and make sure the LGPL v2.1 license is being used properly, and remove the BSD license. And while @jellelicht's input is very much appreciated, I will wait a few more days to see if anyone else can confirm that this path forward is accurate (perhaps @penrods or @jugglinmike).

**Comment by penrods** [comment]
From my perspective I would much rather figure out how to get this migrated to a BSD-type license.  There are things I like about the theory of the *GPL licenses, but in my experience the reality of them is that they limit adoption of technology.

In the [Mycroft project](https://github.com/mycroftai/mycroft-core) we were originally licensed as GPL  After some time it became clear that this was going to kill the project/company trying to build it -- see my blog post from 2017, https://mycroft.ai/blog/right-license/.  I know from personal experience that a small company using GPL code will also be pressured to drop that code (or not get funded) by investors.  And certain regulated industries likely cannot use it on their equipment without getting stuck in a legal catch-22.

Finally, the GPL doesn't really make sense for an non-compiled language.  What does "object code" and "linking" mean for a Python library?  It just isn't a good license for Mycroft, nor do I think it is a good license for any Python library.

_By the way, I'm on the only one who has thought this.  Googling things like "gpl python" finds [this blog](http://aicoder.blogspot.com/2009/08/gpl-and-scripting-languages.html), [this one](https://jacobian.org/2009/jul/13/gpl-questions/) and many [Stack Overflow questions](https://opensource.stackexchange.com/questions/6033/can-a-non-gpl-python-program-use-gpl-python-module).  The fact of the matter is that it is legally ambiguous until somebody goes to court -- and once you are in court you have already lost.  Trust me, I was involved with a fairly small lawsuit once and it cost both companies $1M+ (plus months of my life) to resolve in arbitration and the only winners were the law firms._


So, as you point out it would be kinda easy to just declare websocket-client is back under LGPL v2.1.  But I don't think simple is the right answer for these reasons:
* My arguments above that GPL is not a clear license for Python libraries
* Since Oct 2018 many organizations have adopted `websocket-client` believing it was BSD.  Changing it out from under them seems like a bait-and-switch.  Any which aren't GPL already must either a) ignore the change (illegal), b) accept the change and possibly have to change their own licensing (legal, but lots of repurcussions), c) stop using websocket-client (so pushing many thousands of programmer hours of effort onto other projects).
* 60 commits from 27 people (excluding @liris) have been made under the BSD license.  Just switching their contributions to a GPL license seems sketchy to me.  It looks like there were around 177 commits from 70 different contributors in the years before that while it was under some form of GPL license.
* I don't know the exact motivation for the change to BSD, but there obviously was a desire for that by the principle author -- @liris, who has done the lions share of the work on this library (370 commits and 40k line changes, I'm sure the vast majority of the actual code).  The next closest committer is @engn33r who made all contributions while under BSD.

@allanlewis is the contributor with the most "skin in the game" while it was under a GPL license.  @dimaqq made some significant contributions also, but most other contributors were just a few lines here and there.  I would love to hear from some of these top contributors.

This is a can of worms, I'm afraid.  And there is no simple way to restore it, so let's go for the *desired* outcome, not the simplest one.

**Comment by penrods** [comment]
I forgot to answer a couple things:

> 2. How do we handle contributors who are unresponsive to any license change queries?
I tackled this in Mycroft by @ ing all participants via repo issues, emails (if I could find them), etc.  I used a spreadsheet to track who had contributed, how much (# of commits and lines).  Fortunately, only a single individual objected and it was easy to extract that code -- only a handful of lines.  When I examined most of the non-responsive contributors, the majority of the changes they had made were pretty trivial, like spelling changes.  Morally, I felt decent making the call that they were given a chance to object to the change.

> 3. Does anyone want to help take on this process, either by creating a checklist of what needs to happen or creating a new "Projects" item in this repository? Sounds like it's mostly just reaching out to all contributors, but if anyone wants to offer specific steps, we can set those in motion.
I can assist with pursuing a process similar to the above, if you'd like.

> And has anyone personally experienced issues with this project's licensing in their usage of it? If not, perhaps this isn't a high priority concern at the moment, but I would like to get this resolved at some point.
I know going to any GPL license would force me to stop using this at my current company.  I know that is my personal headache -- not the community's.  But I also am certain I'm not the only one who would have to do so.  I believe investors have become much more educated about licensing concerns.  I also know of a few businesses that had acquisitions delayed or cancelled because of licensing concerns that scared away the purchaser and basically ended up killing the company.

**Comment by jugglinmike** [comment]
Thanks for taking the lead on this, @engn33r!

It might be useful to think of this less as "changing the license back" and more as "reverting the faulty change." As per your timeline, this project was never legitimately licensed BSD. The number of contributors who were led to believe otherwise doesn't affect that.

This is by no means to discredit @penrods's perspective, but I don't believe we can take this mistake as an opportunity to reach their desired outcome. Fortunately, nothing about correcting the error today precludes the option to relicense using a legitimate process.

**Comment by penrods** [comment]
@jugglinmike , no offense taken!  My take for things like this is that the code really belongs to those who wrote it.  As such, I (a non-contributor to this project) have no say in this decision.  I am offering perspective from my past experience and the perspective of other users of the library on the repercussions.

The only people potentially wronged by the license changes were the 70 code contributors pre-change.  The rest of us are just benefiting from their gift to the larger world.  I personally don't see jumping back to the previous license as making them whole -- they have only been actually harmed if they are opposed to the change.  Many of them are likely unaware of this license switch, but certainly not all.  And I don't believe any code contributor has objected yet.

Plus as I said earlier, just reverting to GPL now has the potential of wronging others who contributed code under the believe this was a BSD licensed project.  So their code contributions arguably were licensed as BSD _not_ as GPL.

Like I said, this is a wiggly, wormy issue.

**Comment by jellelicht** [comment]
To correct @penrods ; you can of course relicense most BSD code to (L)GPL.

> 
Plus as I said earlier, just reverting to GPL now has the potential of wronging others who contributed code under the belief this was a BSD licensed project. So their code contributions arguably were licensed as BSD not as GPL. 
> The only people potentially wronged by the license changes were the 70 code contributors pre-change. The rest of us are just benefiting from their gift to the larger world. I personally don't see jumping back to the previous license as making them whole -- they have only been actually harmed if they are opposed to the change. Many of them are likely unaware of this license switch, but certainly not all. And I don't believe any code contributor has objected yet.

Not how licensing works, though! This is not a case with falling trees not making sounds if there is nobody around to hear it; license violations happen when they happen, not retroactively when someone complains about them.

> Plus as I said earlier, just reverting to GPL now has the potential of wronging others who contributed code under the belief this was a BSD licensed project. So their code contributions arguably were licensed as BSD _not_ as GPL.

This is false, please don’t add to the confusion by spreading falsehoods. To clarify that I’m not just being snarky: the BSD license is compatible with the (L)GPL in this direction, so stating that exerting the rights granted under the BSD license is somehow ‘wronging’ somehow is unfair (or honestly misinformed, but please do correct your message, as there is enough FUD on the Web already 😄 ).

**Comment by penrods** [comment]
Hey @jellelicht!  I don't want to dominate this discussion, but I'll go ahead and respond since you mentioned me directly.

I don't believe this is exactly the same as someone taking a licensed library and using it within a differently licensed library.  This is a group of individuals working together on a project, and the rules of that project changed (several times).  So we can't just go back and time and pretend that everyone who contributed the code post-BSD license would have contributed code under an LGPL license also.  (The might have, but we can't assume that.)  And I believe the word "wronged" is appropriate if we do make that decision for them.

License compatibility also doesn't apply here.  You aren't just using the contributed BSD code in a different LGPL library, you are _RELICENSING_ that hunk of code to an LGPL license.  So, theoretically, the contributor might have thought "I really want this code I'm giving to the project to be usable by the world under BSD terms."  If you flip this entire library back to an LGPL license without their permission,  you have removed a BSD version of that code from the world.  This is against the agreement they understood they were contributing under.  So that IS a wrong towards them, at least ethically.  (I am not a lawyer, so I won't say this is definitively true legally, although I'm pretty sure.)

I suppose you could try to identify every line of code that was contributed since October 2018 and mark it as dual license -- the original contributor's BSD license and then the projects LGPL.  But would obviously be a massive mess.  I don't believe you can point to the Github history as a method of identifying which piece is which, I'm pretty sure the license has to be spelled out for the entire work as it stands.  (Although that might require a court case to really determine.)

And, again, the contributors are the only people who have a legal right to complain about any of this.  Each line of code has a copyright belonging to one of them, not me, and not you (I didn't see you on the [contributors list](https://github.com/websocket-client/websocket-client/graphs/contributors), forgive me if I'm wrong about that).  Today they continue to own copyright on each line they submitted to the project, and that agreement to grant the project usage of their copyright was made under an agreed-upon (at the time) license.  Thus even though most of the code in the project was actually still LGPL, the lines contributed by the post 2018 people were given under the understanding it was a BSD license, so that is the license the copyright holder granted.  Only they have the right to change that, not the project as a whole (since there is no CLA or anything in a contributing agreement that grants that right to the project).

I hope this makes sense.  Sorry for being wordy, but I'm trying to be precise (and not snarky either!) and do appreciate the discussion.  This is a flat-out licensing mess and it will require a lot of effort to clean up properly.  That is why I'm advocating for a pause to gain an understanding from all contributors rather than rewriting history and generating more confusion and potential legal mess.

**Comment by allanlewis** [comment]
> @allanlewis is the contributor with the most "skin in the game" while it was under a GPL license.

Thanks for tagging me - I honestly don't have much of an opinion here. I'm no expert on open-source licensing and my contributions to this project are pretty minor. I'm happy with whatever is collectively decided upon.

**Comment by dimaqq** [comment]
A minor contributor here: I'm fine with any OSS license.
(from the technical perspective, I have slight preference for the MIT license, but really any OSS license will do)

**Comment by fuzzyTew** [comment]
Just a comment that as software developers, licensing issues could be a tiring, energy-draining task for people here, since it is not what people came to github to do.  Any way in which people can be more concise, find solutions that others readily accept, or do work to help things out for others, is very helpful.  If licensing isn't quite correct, there are still laws that protect copyright etc.  Things that aren't legally valid simply don't have legal weight, which is not an emergency.

**Comment by jellelicht** [comment]
The only thing that many people here some to forget is that there are two distinct problems:

- What license should this codebase be distributed under?
- What license is this codebase currently (practically and legally) distributed under?

Addressing the first Q is not at all pressing or relevant; addressing the second seems more important. 

`penrods` (trying not to ping) made some very good observations on why the LGPL is perhaps not really suitable for this project, and why it might be a bit iffy to take what contributors intended to be BSD licensed contributions, and integrate them with the actually-LGPL library, which I can certainly understand.

These are all observations about the consequences of re-asserting the LGPL-ness of this library: they are again about a “should” (question 1), and not about addressing question number two, which pertains to “is” (question 2).

**Comment by engn33r** [comment]
First, a big thank you to everyone who commented above - this issue wouldn't have gotten very far without your knowledgeable insights and suggestions!

I spent some time weighing the many perspectives in this issue and decided that the first task is to revert the inaccurate BSD license in this project. As the @penrods mentioned above, this is a licensing mess, and I think reverting an incorrect license change before further time passes is the original intent of this specific issue (based on the title). At the same time, I understand that the LGPL v2.1 license is probably not the best choice for this project for various reasons. Therefore, I opened issue #665 to further discuss which license we should consider moving to. My hope is that we can continue discussion on the idea of a license migration, done properly this time, and determine which specific license would be best for this transition. In my mind, one final license change with all the contributors on board would go a long way towards cleaning up the licensing mess.

So for anyone who has an opinion on which license might be right for this project's future, please do chime in on issue #665!
