### ISSUE TITLE
on_close doesn't get called when the network connection is abruptly cut

### ISSUE THREAD

**Issue by aroshad7** [websocket-client/websocket-client#534]
All the functions of library works just fine except the on_close call back function. I tried the Long-lived Connection Example.

https://github.com/websocket-client/websocket-client/blob/66081be8e0523c9dfaffcb18ba1c8e4765e2288e/examples/echoapp_client.py#L1-L46

and I got this respone.

-----------------------
send: b"\x81\x87\xe9'\x05\x9e\xa1Bi\xf2\x86\x075"
Hello 0
send: b'\x81\x87f\xa2l\\.\xc7\x000\t\x82]'
Hello 1
send: b'\x81\x87>J\xbe\xb2v/\xd2\xdeQj\x8c'
Hello 2
send: b'\x81\x87\n\xc2HiB\xa7$\x05e\xe2{'
Hello 3
send: b'\x81\x87\xc9\xaes:\x81\xcb\x1fV\xa6\x8eG'
Hello 4
send: b'\x81\x87\xbb=\xd0\xea\xf3X\xbc\x86\xd4\x1d\xe5'
Hello 5
send: b"\x81\x87\x88\xc7'\x97\xc0\xa2K\xfb\xe7\xe7\x11"
Hello 6
send: b'\x81\x87\x811\x87\xc4\xc9T\xeb\xa8\xee\x11\xb0'
Hello 7
send: b'\x81\x87R\x13\x19\xa3\x1avu\xcf=3!'
Hello 8
send: b'\x81\x87\xbd:\xac\xdd\xf5_\xc0\xb1\xd2\x1a\x95'
Hello 9
send: b"\x81\x88\x04^\x16\x0bL;zgk~';"
Hello 10
send: b'\x81\x88\n\x85\x12OB\xe0~#e\xa5#~'
send: b'\x81\x88RO\xe8\x8c\x1a*\x84\xe0=o\xd9\xbe'
send: b'\x81\x88\x19%\xd2\x02Q@\xbenv\x05\xe31'
send: b'\x81\x88JE\xf6f\x02 \x9a\n%e\xc7R'
send: b'\x81\x88\xab!\x92\x83\xe3D\xfe\xef\xc4\x01\xa3\xb6'
send: b'\x81\x88\xaa\xa7$\xd0\xe2\xc2H\xbc\xc5\x87\x15\xe6'
send: b'\x81\x88v\x18\xc4\xcd>}\xa8\xa1\x198\xf5\xfa'
send: b'\x81\x88\x9f\xba\xc7\x8b\xd7\xdf\xab\xe7\xf0\x9a\xf6\xb3'
send: b'\x81\x88-\x0f\x81\x98ej\xed\xf4B/\xb0\xa1'
send: b'\x81\x88j\x9di\x04"\xf8\x05h\x05\xbd[4'
send: b'\x81\x88\x86\xdc%\xde\xce\xb9I\xb2\xe9\xfc\x17\xef'
send: b'\x81\x88{X\xe8\xd53=\x84\xb9\x14x\xda\xe7'
send: b'\x81\x88\xf3\x9a/\x85\xbb\xffC\xe9\x9c\xba\x1d\xb6'
send: b'\x81\x88~G\x14\x0f6"xc\x11g&;'
send: b'\x81\x88{\xdde\xcb3\xb8\t\xa7\x14\xfdW\xfe'
send: b'\x81\x88\xc7\x1el\x0e\x8f{\x00b\xa8>^8'
send: b'\x81\x88+Q3Fc4_*Dq\x01q'

Hello 1, 2, 3, ... messages have been echoed back successfully until Hello 10. After that I turned off my Wi-Fi, but the client keeps sending the messages (with no response from server) and on_close doesn't get called. Am I making a mistake or isn't this the intended use of on_close?

**Comment by ajgbarnes** [comment]
I have a similar issue - if I cut switch off the ethernet connection in Ubuntu 18.04, the client still believes the websocket is connected and on_close handler is never called.

**Comment by Indiana3714** [comment]
Yeah theres an issue with WebSocketApp. The lower level create_connection and handling the timeout yourself works fine though

**Comment by engn33r** [comment]
I think the fix detailed in issue #686 may help with a part of the issue described here, but the other part of the issue should be possible to solve by setting the 'ping_interval' and 'ping_timeout' parameters, as outlined in the [documentation for examples](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage).

I was able to recreate the finding that you described, and when I disconnect my wifi, the `run_forever()` function keep running in the background. However, this is expected behavior and everything is working normally, because when I turn on my wifi again, the connection resumes and I continue receiving responses from the server. The `run_forever()` function is supposed to be robust and survive disconnection events by reconnecting when possible, so this is expected behavior. If you actually want a disconnect event to trigger your `on_close()` function (making the connection less robust), you need to set 'ping_interval' and 'ping_timeout' parameters. When the ping timeout parameters are set, the client will recognize that the server did not respond to a regular ping and then trigger the `on_close` callback.

Because I could recreate the issue and outlined a fix that should solve this, I am considering this issue resolved until I hear otherwise.
