### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by ethemkizil** [websocket-client/websocket-client#545]
solved

**Comment by huseyinkomac** [comment]
I am having the same problem. Trying to connect to same host and port from one ip. The first one closes when second one tries to connect.

**Comment by engn33r** [comment]
I think google or stackoverflow is able to answer this better than I can, since the process of connecting multiple websocket clients to a websocket server seems like a more general question and not specific to this particular library. However, it looks like the original poster solved the issue (and edited the original post so I'm not sure exactly what the issue was), so I'll close this since I don't see any problems mentioned relevant to this specific library.
