### ISSUE TITLE
Query : If we re-establish the connection on failure , can we still get the response for already submitted code.

### ISSUE THREAD

**Issue by rayankiy** [websocket-client/websocket-client#555]
HI,
    Below is the scenario where in if I implement a retry web socket connection will help ?

1.  create a Web socket connection and create a channel against spark kernel / session
2. submit a spark code for execution 
3. encounter ws.client.WebSocketException:Flushing frames to the server failed: Connection closed by remote host error
4. re-establish a Web socket connection to the same spark kernel / session
5. Can I expect the response for the request submitted in step 2 ?

**Comment by engn33r** [comment]
Because this is a common question, the general answer is now [in the project FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#if-a-connection-is-re-establish-after-getting-disconnected-does-the-new-connection-continue-where-the-previous-one-dropped-off). If you are specifically working with the unmodified Spark Kernel WebSocket server, I suggest you ask the Spark Kernel team about this question, because it depends on how the server handles a reconnection.
