### ISSUE TITLE
several sockets processing (websocket + zmq) with epoll/select

### ISSUE THREAD

**Issue by vsmelov** [websocket-client/websocket-client#564]
In my application I want to work with messages from/to WebSocket and with ZMQ in the same time (we use ZMQ for internal communication and WebSocket to communicate with front-end).

It would be nice if instead of 

```
app = websocket.WebSocket(...)
app.run_forever()
```

I would be able to do something like

```
def on_ws(): ...
def on_zmq(): ...

app = websocket.WebSocket(..., on_message=on_ws)
zmq = zmq.Socket(..., on_message=on_zmq)


while 1:
    app.run_once()
    zmq.run_once()
```
But I am afraid that in this way I will get 100% CPU usage and whole code will be blocking.

The better idea is:

```
def on_ws(): ...
def on_zmq(): ...

app = websocket.WebSocket(...)
zmq = zmq.Socket(...)

while 1:
    socket = select([app.ws, zmq.socket])
    if socket == app.ws:
        on_ws(app.ws.get())
    if socket == zmq.socket:
        on_zmq(zmq.socket.get())
```

So I always check boths sockets and call specific handler.

Is it possible to combine two sockets processing in one loop?
And what is the proper way (also this way I should handle heartbeats by myself)? 

Can work of `run_forever` be broken down to separate `run_once` calls which will be executed only when the underlying socket is readable?

Thank you :-)

**Comment by gityou123** [comment]
You may want to try asyncio [https://docs.python.org/3/library/asyncio-task.html](https://docs.python.org/3/library/asyncio-task.html)
to handle two different tasks.

**Comment by vsmelov** [comment]
> You may want to try asyncio https://docs.python.org/3/library/asyncio-task.html
> to handle two different tasks.

We don't want to use asyncio since it gives overhead, we do latency-sensitive data processing. That's why we actually try to use synchronous websocket-client :-)

**Comment by engn33r** [comment]
I am a little confused here, so you may need to provide some additional details if I missed your question.

In the code example you shared, it looks like you want to set up two connections in parallel. If you want to have two different connections in parallel, you can do this with multiple threads. Unfortunately [the threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) for this library is not the best, but the documentation is better than it was a year ago (when it didn't exist!)

If you actually want only one connection, you can add `if` statements or other branching logic in your custom `on_message()` function to perform certain actions on WebSocket data and other actions on ZMQ data. This way you only need one connection instead of two connections.

You can examine the [documentation code examples](https://websocket-client.readthedocs.io/en/latest/examples.html) for more ideas.
