### ISSUE TITLE
What is the better way to establish and reconnect to websocket with threads?

### ISSUE THREAD

**Issue by alexnanzer** [websocket-client/websocket-client#580]
Hello @liris and team

we have this:

```
ws_connections = []
func_message = partial(WSClientProtocol.on_message, factory)
ws = websocket.WebSocketApp(
        url,
        on_message=func_message,
        on_error=WSClientProtocol.on_error,
        on_close=WSClientProtocol.on_close,
    )
    ws.on_open = WSClientProtocol.on_open
    ws_connections.append(ws)
    wst = threading.Thread(target=ws.run_forever, kwargs={'ping_interval': 5, 'ping_timeout' : 2})
    wst.daemon = True
    wst.start()
```

**the issues and questions we have**

- as soon the server disconnect the connection due to server restart / maintenance etc., the threaded websockets will be closed and no new data are arriving aswell after restart. 

- there is no log entry after closing the connection. How shall we do to see the reason of closing?

-  There is no automatic reconnect to the server. I have to restart the engine manually. How shall we do to try to reconnect if no connection is given?

thank you in advance. 
Alex

**Comment by kyoforing** [comment]
@alexnanzer 
You can reference this code
It will reconnect to websocket server successfully with threads after server restart

```python
import websocket
import threading, time

def on_close(ws):
    # print('disconnected from server')
    print ("Retry : %s" % time.ctime())
    time.sleep(10)
    connect_websocket() # retry per 10 seconds
def on_open(ws):
    print('connection established')
def connect_websocket():
    ws = websocket.WebSocketApp("ws://127.0.0.1:3000", on_open = on_open, on_close = on_close)
    wst = threading.Thread(target=ws.run_forever)
    wst.daemon = True
    wst.start()

if __name__ == "__main__":
    try:
        connect_websocket()
    except Exception as err:
        print(err)
        print("Socket.io connect failed")
```

**Comment by alexnanzer** [comment]
Thank you for your idea @kyoforing . What I am wondering is: I cannot find this function connect_websocket() in the websocket-client library. So from where do you take it?

**Comment by kyoforing** [comment]
connect_websocket() is custom defined function, not belong websocket-client library

**Comment by ArunEG** [comment]
Hi @kyoforing ,

   You are calling '**connect_websocket**' function from '**on_close**' event will it leads into a deadlock situation ? asking because of on_close  is called by previous thread.

Thanks
Arun Gopi

**Comment by Pauljose97** [comment]
Hi @ArunEG,

Pretty sure that it will lead to a deadlock. I faced the same issue. I fixed mine to some extent by making it single threaded and by putting my websocket connection within on_close function also.
I don't think it's the right way to do it but, I haven't faced the issue since. But recently I've been facing another problem where the client connection closes randomly after a while. In this particular recent case, about 20 days after I started it. Dont know exactly what the issue is, but this is the stacktrace:

Unhandled exception in thread started by <function on_open.<locals>.connection at 0x7f04243847b8>
Traceback (most recent call last):
File "/opt/Storm/script.py", line 482, in connection
returnResponse(ws, False, "Initial connection", "7000", [])
File "/opt/Storm/script.py", line 498, in returnResponse
ws.send(json_data)
File "/usr/local/lib/python3.4/site-packages/websocket/_app.py", line 153, in send
if not self.sock or self.sock.send(data, opcode) == 0:
File "/usr/local/lib/python3.4/site-packages/websocket/_core.py", line 253, in send
return self.send_frame(frame)
File "/usr/local/lib/python3.4/site-packages/websocket/_core.py", line 278, in send_frame
l = self._send(data)
File "/usr/local/lib/python3.4/site-packages/websocket/_core.py", line 448, in _send
return send(self.sock, data)
File "/usr/local/lib/python3.4/site-packages/websocket/_socket.py", line 135, in send
raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
send: b"\x81\xfe\x00\xa9A<;V:\x1eV%&\x7fT2$\x1e\x01vc\x0b\x0bfq\x1e\x17vcTT%5RZ;$\x1e\x01vc\r\x0bxs\x0e\x15dr\x12\tbr\x1e\x17vcOB%5YV\x15.R]?&\x1e\x01v:\x1eX93YHt{\x1c\x19dc\x10\x1bt,YV93E\x19la\x04Fza\x1eI32LT82Y\x19la\x1er8(HR7-\x1cX9/R^55UT8c\x10\x1bt3YH&.RH3\x04NI93\x1e\x01v']W%$\x10\x1bt5SK9-S\\/\x08xHt{\x1c`\x0b<"

Any suggestions or a reason as to why it might have happened?

Thanks,
Paul

**Comment by alexnanzer** [comment]
What I have seen is, that when I try with the version from @kyoforing, it starts a new thread. From that point, it works and connect will be re-estabished, BUT: The memory increases when I simulate a on_close every 2 seconds. I guess this is because the initial on_close() can never finish its work.

@Pauljose97 I resolved that doing a ping to the server and store the answer-time into a local variable "restart". If three times no answer is coming back, then on_close() and change "restart" to 1. In a separate thread monitor "restar" and if 1, try to reconnect.

**Comment by ArunEG** [comment]
@alexnanzer @kyoforing @Pauljose97 

As I understands calling connect_websocket from on_close is not a good idea also it will leads in to out of memory situation, Instead of doing this way,  You can call **run_forever** in a threaded  while loop. Whenever any error happens the loop will try to re establish the connection. it works well for me
```
def __create_ws(self):
        while True:
            try:
                websocket.enableTrace(False)
                self.__WSCONNECTION = websocket.WebSocketApp(url,
                                          on_message = self.__on_message,
                                          on_error = self.__on_error,
                                          on_close = self.__on_close,
                                          header=self.header)
                self.__WSCONNECTION.on_open = self.__on_open
                self.__WSCONNECTION.run_forever(skip_utf8_validation=True,ping_interval=10,ping_timeout=8)
            except Exception as e:
                gc.collect()
                log.debug("Websocket connection Error  : {0}".format(e))                    
            log.debug("Reconnecting websocket  after 5 sec")
            time.sleep(5)
```

Happy Coding
Thanks
Arun Gopi

**Comment by Pauljose97** [comment]
@alexnanzer Thanks for the input. Seems like a good suggestion. Should work. Will implement it today. Thanks again.
@ArunEG True, calling connect() from on_close() isn't a good idea as it keeps getting nested over time and increasing memory. Although I was already running ws.run_forever() I hadn't passed any arguments to it. But this is a much better approach. Just getting started with python and I didn't know that run_forever() was a non returning function till close. I tested out your method and it works 100% fine. Thanks :)

Thanks,
Paul

**Comment by ArunEG** [comment]
You are welcome, it is great to see that the community is bigger and bidder day by day :) . thanks @liris

**Comment by IbrahimBond** [comment]
@ArunEG thanks for sharing your code. 
does the exception work for you? it keeps getting skipped for me.

**Comment by Bugrachi** [comment]
> ```python
> connect_websocket
> ```
Small correction
Instead of this
wst = threading.Thread(target=ws.run_forever)
Use that
wst = threading.Thread(target=ws.run_forever())

**Comment by Bugrachi** [comment]
> @alexnanzer
> You can reference this code
> It will reconnect to websocket server successfully with threads after server restart
> 
> ```python
> import websocket
> import threading, time
> 
> def on_close(ws):
>     # print('disconnected from server')
>     print ("Retry : %s" % time.ctime())
>     time.sleep(10)
>     connect_websocket() # retry per 10 seconds
> def on_open(ws):
>     print('connection established')
> def connect_websocket():
>     ws = websocket.WebSocketApp("ws://127.0.0.1:3000", on_open = on_open, on_close = on_close)
>     wst = threading.Thread(target=ws.run_forever)
>     wst.daemon = True
>     wst.start()
> 
> if __name__ == "__main__":
>     try:
>         connect_websocket()
>     except Exception as err:
>         print(err)
>         print("connect failed")
> ```

Small correction
Instead of this
wst = threading.Thread(target=ws.run_forever)
Use that
wst = threading.Thread(target=ws.run_forever())

**Comment by maxim-kukushkin** [comment]
I don't understand. The documentation says:
`The WebSocketApp run_forever loop automatically tries to reconnect when a connection is lost, and provides a variety of event-based connection controls.`
In what sense manually coding the close handling and managing threads is "automatic"? What's the point of `run_forever` function then vs. simple `while` loop with `.recv()` inside and simple exception handling? Also, why is it called "forever", if it exits on the first connection error?

**Comment by engn33r** [comment]
@maxim-kukushkin I will try to answer your questions one at a time. If you encounter additional issues using `run_forever()` in your use cases, it might be best to create a new issue.

> In what sense manually coding the close handling and managing threads is "automatically"? What's the point of run_forever function then vs. simple while loop with .recv() inside and simple exception handling?

If you want to see exactly what the run_forever() function does, I suggest examining the relevant [_app.py](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py) code. The [examples documentation page](https://websocket-client.readthedocs.io/en/latest/examples.html) shows some ways that the WebSocketApp run_forever() function differs from the .send()/.recv() approach.

> Also, why is it called "forever", if it exits on the first connection error?

The run_forever() function shouldn't exit on the first error. This issue was created to discuss an unexpected behavior or edge case. The project's [threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html), which relates to this issue, is still a work in progress.

> The example in the readme also doesn't mention the need to manage "close" event in some sophisticated way - there, one single call to run_forever() is enough

The [examples documentation page](https://websocket-client.readthedocs.io/en/latest/examples.html) has more examples. I updated the README to emphasize this URL.

**Comment by FelixOutta** [comment]
some error I encountered which seems weird in my opinion and will leave here as reference:

when I call     `wst = threading.Thread(target=ws.run_forever())` it want start the thread it will just start the method right away and dont return from it.

so using it without () like 
`wst = threading.Thread(target=ws.run_forever)`
 is important for the thread to know that the method was passed to be started async.

**Comment by engn33r** [comment]
To settle questions around using `target=ws.run_forever()` or `target=ws.run_forever`, my understanding is that using `target=ws.run_forever` is the correct approach. This is what is used in the bin/wsdump.py example in this project. The [threading.Thread documentation](https://docs.python.org/3/library/threading.html#threading.Thread) states the target should be a callable function. threading.Thread has a separate `args` parameter where args should be placed, as seen in [the _app.py file](https://github.com/websocket-client/websocket-client/blob/11893bc746913f7bfeb85db62dfa6f0c2a1deb6e/websocket/_app.py#L327) of this project.

**Comment by kant777** [comment]
The documentation say this "The WebSocketApp run_forever loop automatically tries to reconnect when a connection is lost, and provides a variety of event-based connection controls" . is this true? if so where can I see the code for reconnection? and if this is true why do we need to handle reconnect ourselves as other folks are talking about in this thread?

**Comment by engn33r** [comment]
@kant777 oddly enough, the code that I recalled seeing in either an old issue or old commit doesn't appear to be in the current code base. I'll have to look into this further. If anyone wants to investigate old commits and changes to the `run_forever()` function and share their findings, that would be great, otherwise I'll aim to get around to this in the next month or so.

**Comment by engn33r** [comment]
I will provide a brief history on this even though my understanding of the details is still incomplete. In short, it's possible that either 1. run_forever does not automatically reconnect as claimed or 2. this functionality may need to be rebuilt or repaired due to accidental changes made over time. I would like someone to outline repeatable steps to demonstrate whether the current `run_forever()` function works correctly with the result they get vs, expected behavior.

Back in 2013, the `run_forever()` function as seen in #52 used the `keep_running` boolean. This was used in the while loop `while self.keep_running` to continue looping the line of code `data = self.sock.recv()` as long as `keep_running` was true. I do not see any automatic reconnect in this code.

In 2015, the `run_forever()` function as seen in #143 switch the while loop to use `self.sock.connected` and not `keep_running`. But I still do not see any automatic reconnect.

In 2018, #375 heavily modified the way that the `run_forever()` function works. #389 mentions a new dispatcher interface. The "rel" dependency no longer exists in websocket_client, but the dispatcher functions do. However, I did recently modify the dispatcher functions while fixing #752, which may have impacted how they function. It would be great if @bubbleboy14 could comment on whether the current `run_forever()` function code is functioning in the same way as it was intended back in 2018.

I look forward to other comments. The easiest fix may be to remove the claim that `run_forever` is an infinite loop and automatically reconnects.

**Comment by bubbleboy14** [comment]
Hello @engn33r and all. I just tested 1.2.1 against two examples. One uses run_forever(), and the other uses run_forever(dispatcher=rel), and they both work fine as far as I can tell. I turned my wifi off and on, and it reconnected without issue.

I then tested 1.2.2 against the same two examples. The run_forever(dispatcher=rel) example still works, but the bare run_forever() example does not. I believe this is due to this recent commit:

https://github.com/websocket-client/websocket-client/commit/998c496343fc4fdeb8d2714034906e6d0dc6ba6e

which removed the read() functions from Dispatcher and SSLDispatcher.

So as of 11 days ago, run_forever() (without kwargs) no longer works for me. I only use websocket-client with rel (so my stuff still works) but I'm surprised it's still working for others.

**Comment by engn33r** [comment]
Thanks @bubbleboy14. I don't think the [example docs](https://websocket-client.readthedocs.io/en/latest/examples.html) contain an example of `run_forever(dispatcher=rel)`, so it someone wants to submit a PR (I think I saw an example of this mentioned in an old issue or PR), that should help to clarify things a bit. And unfortunately commit 998c496 introduced a bug that was noted in issue #769 and should be reverted in v1.2.3.

**Comment by bubbleboy14** [comment]
Here's a PR @engn33r:

https://github.com/websocket-client/websocket-client/pull/770

LMK if anything is missing or unclear.

**Comment by engn33r** [comment]
Thanks to @bubbleboy14 I have updated the documentation around `run_forever()`, including the README example, to mention the necessity for a dispatcher parameter to get the full automatic reconnect functionality. If anyone is still having issues with `run_forever()`, please open a new issue.

**Comment by ChumKiu** [comment]
I've did the following solution, let me know if have some drawback and how it can be optimized.

```
"""
Usage:
	python ffscktest_nonblocking.py

Python version:
	- checked on Python 3.8.5
"""

import os
import sys
import time

import websocket
import threading

class espWebSocketClass(threading.Thread):

	# Indirizzo IP ESP32 e porta WebSocket
	ESP32_IP_ADDRESS = "192.168.2.199"
	ESP32_WS_PORT="6000"
	
	# Timeout (in secondi) ricezione risposta dopo tx comando
	RX_TIMEOUT = 5
	# Numero massimo tentativi ritrasmissione comando
	MAX_TX_CMD_RETRY = 5
	
	wsptr = None
	wsptr_open = False
	
	rx_message_ok = False
	rx_message_text = ""
	
	def __init__(self, **kwds):
		threading.Thread.__init__(self, **kwds)
		return

	def run(self):
		while(True):
			try:
				print("(" + self.name + " - run) START THREAD!!")
				websocket.setdefaulttimeout(5)
				ws = websocket.WebSocketApp("ws://"+self.ESP32_IP_ADDRESS+":"+self.ESP32_WS_PORT,
															on_open = self.on_open,
															on_message = self.on_message,
															on_error = self.on_error,
															on_close = self.on_close,
															)
				self.wsptr = ws
				ws.run_forever(ping_interval = 10, ping_timeout = 5)
				print("(" + self.name + " - run) Restart connection...")
				time.sleep(1)
			except Exception as ex:
				print("(" + self.name + " - run) An exception of type", type(ex).__name__, "occured. Arguments:", ex.args)
				sys.stdout.flush()
				pass
		return

	def on_message(self, ws, message):
		self.rx_message_text = message
		self.rx_message_ok = True
		
		print("(" + self.name + ") RX:" + message)
		sys.stdout.flush()
		return

	def on_error(self, ws, error):
		print(error)
		return

	def on_close(self, ws, close_status_code, close_msg):
		self.wsptr_open = False
		print("(" + self.name + " - on_close) WebSocket closed!")
		sys.stdout.flush()
		return
		
	def is_ws_connected(self):
		return(self.wsptr_open)

	def on_open(self, ws):
		self.wsptr_open = True
		print("(" + self.name + " - on_open) Websocket connection opened!")
		sys.stdout.flush()
		return
		
	def send_message(self, message):
		self.rx_message_ok = False
		self.rx_message_text = ""
		
		is_timeout = False
		is_exception = False
		
		loc_rx_message_ok = False
		loc_rx_message_text = ""
		
		# Command retry if timeout or exception
		cur_retry_ctr = 0
		while(cur_retry_ctr < self.MAX_TX_CMD_RETRY):
			
			try:
				print("(" + self.name + " - send_message) TX:" + msg)
				sys.stdout.flush()
				self.wsptr.send(message)
			except Exception as ex:
				is_exception = True
				print("(" + self.name + " - send_message) An exception of type", type(ex).__name__, "occured. Arguments:", ex.args)
				sys.stdout.flush()
			
			# No exception arise, we can wait for some answer with timeout
			if (not is_exception):
				is_timeout, loc_rx_message_ok, loc_rx_message_text = self.wait_timeout(self.RX_TIMEOUT)
			
			# Timeout or exception so retry to send the command
			if ((is_timeout) or (is_exception)):
				cur_retry_ctr = cur_retry_ctr + 1
				
			if (loc_rx_message_ok):
				break;
			
		return(is_exception, is_timeout, cur_retry_ctr, loc_rx_message_ok, loc_rx_message_text)
		
	def wait_timeout(self, timeout):
		is_timeout = False
		
		loc_rx_message_ok = False
		loc_rx_message_text = ""
		
		time_started = time.time()
		while(True):
			if (time.time() > time_started + timeout):
				is_timeout = True
				loc_rx_message_text = ""
				loc_rx_message_ok = False
				break
			if (self.rx_message_ok):
				is_timeout = False
				loc_rx_message_ok = self.rx_message_ok
				loc_rx_message_text = self.rx_message_text
				break
			pass
		return(is_timeout, loc_rx_message_ok, loc_rx_message_text)

# --------------------------------------------------
# MAIN
# --------------------------------------------------
if __name__ == "__main__":
	
	wst = espWebSocketClass(name = "wsThread")
	wst.setDaemon(True)
	wst.start()
	
	error_counter = 0
	timeout_counter = 0
	rx_ok_counter = 0
	
	while(True):
		
		try:
			print("(main) LOOP")
			sys.stdout.flush()
			
			# Check if WebSocket is connected to send data over it
			if (wst.is_ws_connected()):
				msg="test"
				err, timeout, retry_ctr, rx_ok, rx_msg = wst.send_message(msg)
				if (err):
					error_counter = error_counter + 1
					print("(main) ERROR exception!")
					sys.stdout.flush()
				else:
					if (timeout):
						timeout_counter = timeout_counter + 1
						print("(main) RX ERROR timeout!")
						sys.stdout.flush()
					elif (rx_ok):
						rx_ok_counter = rx_ok_counter + 1
						print("(main) RX OK! => msg: " + rx_msg)
						sys.stdout.flush()
				# Debug
				print("Exception,Timeout,Retry,RxOk: " + str(error_counter) + " - " + str(timeout_counter) + " - " + str(retry_ctr) + " - " + str(rx_ok_counter))
			else:
				# WebSocket not connected
				pass
				
		except Exception as ex:
			template = "(main) An exception of type {0} occured. Arguments:\n{1!r}"
			message = template.format(type(ex).__name__, ex.args)
			print(message)
			sys.stdout.flush()
			sys.exit(0)
```

Thanks and best regards.
ChumKiu

**Comment by bubbleboy14** [comment]
@ChumKiu now you can pass reconnect to run_forever(): https://github.com/websocket-client/websocket-client/blob/52329c4956f88133f45ecd510668776cd8a96ebf/websocket/_app.py#L298

So `run_forever(reconnect=5)` will automatically reconnect after waiting 5 seconds.

LMK if that works for you!
