### ISSUE TITLE
Server is sending wrong opcodes

### ISSUE THREAD

**Issue by Masha-L** [websocket-client/websocket-client#583]
I'm writing a client-side script and use a provided server that I have no power over.

As far as I can tell, it sends the wrong opcodes: when it sends several continuous frames it sends them with the opcode ABNF OPCODE_TEXT (2) and a flag fin indicating that the message is not done which results in an "Illegal frame" error (the client receives a message, validates the first frame, expects to receive a second one with OPCODE_CONT (0), instead receives a new frame with OPCODE_TEXT (2) and throws an exception).

I found two ways to work around it,  both include modifying the websocket-client files

1) Comment out the validation case in _abnf.py file, lines 421-423 
` if self.recving_frames and \
                frame.opcode in (ABNF.OPCODE_TEXT, ABNF.OPCODE_BINARY):
            raise WebSocketProtocolException("Illegal frame")`

2)Or adding a flag to recv_data_frame method in _core.py to indicate if the script is encountering the issue, described above. If so, replace the opcode from the server to OPCODE_CONT for all the messages after 1st one.

There are obvious downsides for both approaches and I was wondering if anyone might have some advice on how to go about this without hacking existing libraries :)

**Comment by engn33r** [comment]
If the server isn't complying with the RFC-6455 specification, a customized solution is probably the best way forward.  If the server happens to have an old version of the WebSocket spec implemented, there's a chance an old version of a client library might work. I'll close this issue for now since it's a server issue and not a particular issue with this library (as far as I can tell), but others can continue to comment ideas if they have solutions. Alternatively, you might try asking on stackoverflow.
