### ISSUE TITLE
Loosing packets when re-establishing new conntion

### ISSUE THREAD

**Issue by ArunEG** [websocket-client/websocket-client#600]
Hi

When websocket client re-establish the connection due to some error, all the packets are queued in the rx or tx in previous TCP connection will loose, Is there any way to reuse the tx and rx queue for new TCP connection.
```
root@N100AR netstat -na | grep <port>
tcp        0      0 56.94.213.17:48402      <dest ip:port    ESTABLISHED 
tcp        0  **63288** 56.122.33.2:60306       <dest ip:port    FIN_WAIT1 

```
Thanks
Arun G

**Comment by engn33r** [comment]
Because this is a common question, the general answer is now [in the project FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#if-a-connection-is-re-establish-after-getting-disconnected-does-the-new-connection-continue-where-the-previous-one-dropped-off). This question is similar to #555.

It might be possible to copy the tx and rx socket data between sockets in the operating system, but this is outside the scope of the WebSocket protocol and the websocket-client project.
