### ISSUE TITLE
WebSocketAddressException: Name or service not known

### ISSUE THREAD

**Issue by and7ey** [websocket-client/websocket-client#602]
I am running websocket-client on Google App Engine (GAE).

Sometimes it works well. But usually, it gives the following error - 

```
File "/base/data/home/apps/g~app/my-app.py", line 115, in send_text
    ws.connect(str(device_address))
  File "libs/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "libs/websocket/_http.py", line 114, in connect
    hostname, port, is_secure, proxy)
  File "libs/websocket/_http.py", line 158, in _get_addrinfo_list
    raise WebSocketAddressException(e)
WebSocketAddressException: [Errno -2] Name or service not known
```

There is no problem with the server - it happens with different servers. And sometimes it works with exactly the same server. The problem is either with GAE or with websocket-client, but I don't understand how to investigate it further.

**Comment by c-tanner** [comment]
Any resolution to this? We're facing the same error.

**Comment by and7ey** [comment]
Try to enable billing in your GAE project. If I remember correctly, it fixed the problem.

**Comment by engn33r** [comment]
@c-tanner @and7ey I'll close out this issue for now because it seems like the and7ey resolved the issue, but @c-tanner if you are able to confirm that enabling billing for a GAE project resolved this, it would be great to add better closure around this. We could consider adding some details around GAE usage in the documentation depending on how different that environment is
