### ISSUE TITLE
cant send large messages

### ISSUE THREAD

**Issue by King181** [websocket-client/websocket-client#603]
im trying to send a large message with ws.send, but it is not sending, and it stops the entire connection.

**Comment by chenkaiC4** [comment]
me too. did you find the way to work out?

**Comment by King181** [comment]
nope

**Comment by csimons** [comment]
Did some testing.  The limit seems to be 2048 bytes.

**Comment by engn33r** [comment]
Thanks for highlighting this issue. Would either @King181 or @chenkaiC4 be willing to post a [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of your connection here to add additional context to this issue? If you could share how large the message is that you are trying to send, what options you are using for the connection, etc., this would help. Issue #633 mentioned the a message of between 5,000 and 10,000 chars could trigger this.

For future reference, this issue may be related to #206

**Comment by engn33r** [comment]
I tried to replicate this error with the latest code, Python 3.8.5, and a 15,000 char payload. I was unable to replicate the issue. I'm including the code I used to test this below, for demonstration purposes. I'll close this issue for now, because I can't replicate this issue, but we can reopen this issue if someone encounters it again and posts additional details to recreate the problem. One commonly encountered exception is #557, where the connection is closed when you try to use it. This can sometimes be because the server ends the connection, for one reason or another. You can also look at the [documentation's examples](https://websocket-client.readthedocs.io/en/latest/examples.html) for other tips and sample code for this library.

```python
import websocket

# Enable trace for debugging
websocket.enableTrace(True)

# Generate long payload of 15,000 char
longpayload="a"
for i in range(1, 15000):
    longpayload = longpayload + "a"

# Try sending long payload and print a message if error encountered
try:
    ws = websocket.WebSocket()
    ws.connect("ws://echo.websocket.org") # Replace this URL with server of choice
    ws.send(longpayload)
    ws.close()
except:
    print("Sending long payload caused an error!")
```
