### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by jwiebels** [websocket-client/websocket-client#607]
Hello,

I am trying to create >1024 WebSocketApps with my code, but after surpassing ~1016 open connections, I receive the error `filedescriptor out of range in select()`.

After googling and browsing old issues, namely #293, #375 and #561, I found that the proposed solutions do not seem to work for me.

I'm running
- Linux Debian GNU/Linux 10 (buster), Kernel Linux 4.19.0-8-amd64
- Python 3.7.6

and am calling the following code from my application:
```Python
class ExampleCode:
    def __init__(self, custom_url):
        self.socket = websocket.WebSocketApp(url=custom_url, on_error=self._on_error)
        self.socket.run_forever()

    def _on_error(self, error):
        print(error)       # implemented logger in real code, print() for simplicity here
```

and added this snippet to `websocket\_app.py`:
```Python
class PollDispatcher:
    def __init__(self, app, ping_timeout):
        self.app = app
        self.ping_timeout = ping_timeout

        self.poller = select.poll()
        READ_FLAGS = (select.POLLIN | select.POLLPRI | select.POLLHUP | select.POLLERR)
        self.poller.register(self.app.sock, READ_FLAGS)

    def read(self, sock, read_callback, check_callback):
        while self.app.keep_running:
            events = self.poller.poll(self.ping_timeout)
            if events:
                if not read_callback():
                    break
            check_callback()
```

Furthermore, I edited the `WebSocketApp.create_dispatcher()` method to always return a `PollDispatcher` object:
```Python
   def create_dispatcher(self, ping_timeout):
        timeout = ping_timeout or 10

        return PollDispatcher(self, timeout)
```

When I now start my application, the desired amount of connections are being built, but after a time `_on_error` starts spewing "[Errno 32] Broken Pipe".
I'm sure that I have just implemented the sample code wrongly, but want to ask, if you could provide an updated version of this code publicly for users to implement or make selecting a `PollDispatcher` easier in the future?

Thanks for your attention!

Best regards,
Jan

**Comment by chwba** [comment]
This would also interest me very much I have the same problem/situation

**Comment by chwba** [comment]
The question is if this happens due to some mishandling of the unix pipe inside the library? https://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python

**Comment by WobinRho** [comment]
I'm having the same issue. Fix pls.

**Comment by chwba** [comment]
well, seems like I have to do it myself, because we cant rely on this lib.

**Comment by jwiebels** [comment]
Hi, it's been 11 days. Would love a quick answer, even if it's a "Sorry, we cannot work on this at the moment". Thanks!

**Comment by chwba** [comment]
best library, lets just not reply to issues

**Comment by yravid** [comment]
I managed to overcome this limit by using custom dispatcher. checkout https://github.com/websocket-client/websocket-client/pull/568 and there's an option to pass a dispatcher (without changing the source) https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_app.py#L177

**Comment by engn33r** [comment]
Hi everyone, this repository is getting a reboot and it might take a while for me to get to some of the more involved issues like this one. In the meantime, it might be worth checking if any of the existing PRs (like 568) might resolve this for you. Thanks for posting the info above and we'll get this resolved in due time!

**Comment by jwiebels** [comment]
Alright, thank you, @engn33r.

**Comment by engn33r** [comment]
I [found this similar issue](https://github.com/ratchetphp/Ratchet/issues/300) and [this other similar issue](https://github.com/ghedipunk/PHP-Websockets/issues/104) in other websocket server libraries. I would guess that if you run the command `ulimit -n` on your *nix system, you will see a limit of 1024. There are [many](https://beyondco.de/docs/laravel-websockets/faq/deploying#open-connection-limit) [different](https://centrifugal.github.io/centrifugo/blog/scaling_websocket/#os-tuning) articles online explaining how to change the ulimit value. Let us know if that solves it for you! If that doesn't fix things, try searching for "websocket server 1024 connections", "websocket benchmarking", or "websocket scaling" for other solutions.

I don't think there is anything in this project's code that sets a limit of 1024, so this issue is something related to the operating system, websocket server, proxy, or other limiting factors. I think stackoverflow or another forum may be a better place to ask for these broader questions, but if you have additional information about your setup, you are welcome to share.
