### ISSUE TITLE
Create an Example for file uploading

### ISSUE THREAD

**Issue by Geogouz** [websocket-client/websocket-client#625]
Can someone create an example for a client that uploads a big file (e.g. 200MB) to a Server?
What is the best approach for that? I tried to do one by splitting the file into byte-array chunks of fixed size (e.g. 16384bytes) and sending those chunks one by one within a for a loop. On the server, I track the number of received chunks and as soon as I have received all of them, I do a checksum to ensure I received it correctly. However, using my approach,  if the connection is noisy, then the socket connection dies and the client stops sending chunks.

You can see the reported problem here:
https://stackoverflow.com/questions/63107715/brokenpipeerror-errno-32-broken-pipe-when-sending-many-big-frames-using-web

**Comment by engn33r** [comment]
While it would be nice to see an example of such functionality in this project, I don't think it would be a good fit. The WebSocket specification does not outline a specific approach to transferring files over WebSockets. So to implement file transfers over WebSockets, you would need to have both client AND server code to coordinate the file transfer. A simple WebSocket echo server, like the one at http://websocket.org/echo.html, does not allow for file transfers. Since this library is only a client-side library, I think your question is more appropriate for stackoverflow or for another WebSockets library that supports both client and server communications. However, you might find some useful information in the source code of projects that [depend on the websocket-client library](https://websocket-client.readthedocs.io/en/latest/examples.html#real-world-examples). For example, the Slack API has a [files.upload function](https://api.slack.com/methods/files.upload) and some Slack projects use this library.
