### ISSUE TITLE
cant change connection's protocol 

### ISSUE THREAD

**Issue by staywithdream** [websocket-client/websocket-client#634]
1. cant change connection's protocol  if you set the connection's protocol is wss://
2. the protocol name input widget never change , the icon is right
![image](https://user-images.githubusercontent.com/40335088/92124419-57606f00-ee30-11ea-8b55-dce890c94a3e.png)

**Comment by engn33r** [comment]
Sorry, I think you may have found the wrong project, even though the names are very similar. It looks like you are using the Mac app featured on this website: https://websocket-client.com. I would suggest you reach out to this other application's development team, since this repository does not contain a Mac GUI application
