### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

### ISSUE THREAD

**Issue by Sriram21** [websocket-client/websocket-client#650]
Hi,

Getting the above error only when i initiate a websocket connection.. 
Python version tested : 2.7 , 3.3 , 3.6 and 3.8
OpenSSL tested : 1.0.1k , 1.1.1d

Anyone suggest me a fix for it ? 

Regards,
Sriram

**Comment by lt94** [comment]
> Hi,
> 
> Getting the above error only when i initiate a websocket connection..
> Python version tested : 2.7 , 3.3 , 3.6 and 3.8
> OpenSSL tested : 1.0.1k , 1.1.1d
> 
> Anyone suggest me a fix for it ?
> 
> Regards,
> Sriram

got same error~~

**Comment by Sriram21** [comment]
Hi @lt94 ,

Thanks for the above suggestion.

By doing so are we not making the connection insecure ? If it is a local setup we can try that but what happens if external connections are made ?

**Comment by engn33r** [comment]
@Sriram21 the sslopt argument should resolve this. The example that @lt94 mentioned is also found in [the README](https://github.com/websocket-client/websocket-client#how-to-disable-ssl-cert-verification). If you are using this argument and the issue still appears, and you have reviewed the README, you are welcome to reopen the issue with further details to help us recreate the error.

SSL certificate verification is the process of checking a certificate against a list of trusted certificates. Sometimes this error occurs because the server's certificate is not in the client's list of trusted certificates. Using ssl.CERT_NONE does not automatically mean the connection is insecure - the connection can still be encrypted normally. ssl.CERT_NONE only means that the server's certificate will not be checked against the list of trusted certificates. You can google "ssl certificate verification process" for more information.
