### ISSUE TITLE
Project upgrade initiative

### ISSUE THREAD

**Issue by engn33r** [websocket-client/websocket-client#660]
Hello and welcome! :wave:

You may have noticed that this repository has been in hibernation for a while, but it is in the process of being revitalized! After all, this amazing library is one of the [top 100 most downloaded Python modules](https://hugovk.github.io/top-pypi-packages/). As the new project maintainer (as of Jan 2021), I'm working on a few upgrades for this project, and there are many ways that you can help out! Here's a few ideas, but this list will change over time as we continue making progress here :raised_hands::raised_hands:

- The [new documentation](https://websocket-client.readthedocs.io/en/latest/) needs more details! If you have code snippets that can be added to the [examples](https://websocket-client.readthedocs.io/en/latest/examples.html) section, or problems that you already overcame that can go in the [FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html), your input would be appreciated! :tada:
- If you are familiar with past issues in this project, there's a lot of dust that needs cleaning up! Bonus points if you can add to the [new documentation](https://websocket-client.readthedocs.io/en/latest/) and reference the documentation to close an issue :star:
- The [autobahn test code](https://github.com/websocket-client/websocket-client/blob/bdfdf4d7c8f14bb751cabdaf5f4171d98cf88669/compliance/test_fuzzingclient.py) in this project, under the compliance directory, uses an old autobahn installation method. It would be great to update this so we can keep track of performance improvements as the code changes. :+1:
- Are you familiar with GitHub Actions or CI best practices? Any additional automated tests that can streamline the process of testing new code would make it easier to apply upgrades. :sunglasses:
- Are you a Python 3 user? You should be! Python 2 was EOL in January 2021, but this project was focused on supporting Python 2 in the past. The migration to Python 3 is a work in progress, as is the migration away from focusing on Python 2, so if you see improvements here, please submit a PR. :smile:

Any other contributions are welcome! If you have any questions, concerns, or suggestions, just create an issue here and share your thoughts.

**Comment by lalondesteve** [comment]
How brutal would you like the python3 transition to be? Should we assume that python2 is unsupported from now on?

**Comment by engn33r** [comment]
Thanks for the question. I am undecided about Python 2 support. I can point to issue #443 as evidence that we should probably support Python 2 past EOL. I will tentatively say support for Python 2 should aim for at least 6 months past EOL, but maybe up to 1 year given some enterprise systems are only updated annually. These are just my first thoughts and I am happy to change plans, because I don't have any metrics around who exactly is using this library with Python 2 right now. If there are certain PRs that would break Python 2 support, you can create an issue or example PR and we can discuss a specific change in depth. In general, Python 3 support is a more important goal than Python 2 backwards compatibility, and deprecated functions should be upgraded wherever possible.

**Comment by Codeglitches** [comment]
How about creating a maintenance branch just for bug fixes which will still support python 2.7 and stays on version 0.x
And start working on a 1.0 version which drops python 2 support (as it breaks backward compatibility it is quite common to update the major version number). 
Dropping python 2 would be a good time to clean up the code, get better unittests, flake8 tests, etc so you would start 1.0 with a cleaner codebase.

**Comment by engn33r** [comment]
Good idea, I am in favor of a separate 2.7 branch for those that need backwards compatibility. This project isn't actively using any branches at the moment, which is something that could be improved. @Codeglitches if you want to link to a project that does something similar, or a project with guidelines explaining this split for future contributors, it would be preferable to reuse rather than recreate. I am planning on releasing a version 1.0.0 in the next month or so because semantic versioning also hasn't been properly followed (see #669), but I am not sure if keeping Python 2 at 0.X and Python 3 at 1.X is better than moving Python 2 to 1.X and Python 3 to 2.X, or keeping them the same major version but different branches, or some other variation. If no one else wants to jump in, I'll aim to split off a Python 2 branch in early/mid April.

**Comment by Codeglitches** [comment]
I don't have a specific project in mind that does this. I see a lot of projects just dropping support for 2.7 and not bothering to maintain code for EOL python version. But working with branches it is basic git functionality so it should not be to hard to find a good way what works for you. Be sure, to only accept bugfixes for the 2.7 branch otherwise maintaining the branch will take to much of your time.

The breaking change with 0.58 is an issue that cannot be easily fixed by publishing an 1.0 version as the damage is already done. I  would suggest restoring the api a.s.a.p. and pushing an 0.59 version that fixes it in stead of now publishing a 1.0 version for a break that has already happened.

For dropping python 2, I would suggest creating a separate branch for the current 0.58 / 0.59 version and only allow bugfixes on that branch. All new functionality goes to master and works towards a 1.0 version. This version can break the api by dropping python version < 3.6. It also gives you the opportunity to investigate the 'inherance' issue and really fix it once and for all. If possible fix it without breaking the api, but if you can't, break it.

Before publishing a 1.0 version I would set some goals, which should be met before releasing like:
* All dependencies for 2.7 support (six) are removed.
* 80% code coverage by unittests
* All code passes flake8
* Unittests and Flake8 are run automatically for each merge request

This will give you a better basis to keep maintaining the code base.

**Comment by engn33r** [comment]
@Codeglitches @lalondesteve I released v0.59.0, which is the last main release to support Python 2. So go ahead and make some PRs if you want to help with the Python 3 transition. I got a start on removing a lot of six dependency code, but I didn't finish and I'm sure there's other items I am unaware of.

I am closing this issue in favor of the newer issue #684, which continues on the same topic concerning next steps for this project.
