### ISSUE TITLE
missing 1 required positional argument: 'error'

### ISSUE THREAD

**Issue by the-anonymous009** [websocket-client/websocket-client#664]
```python
import logging

import websocket


class A:
    def __init__(self):
        pass

    def on_error(self, ws, error):
        pass


def main():
    logging.basicConfig(level=logging.DEBUG)
    a = A()
    ws = websocket.WebSocketApp("ws://test",
                                on_error=a.on_error)

    ws.run_forever()


if __name__ == '__main__':
    main()
```
This code generate error message saying "ERROR:websocket:error from callback <bound method A.on_error of <__main__.A object at 0x7f3565769190>>: on_error() missing 1 required positional argument: 'error'".  I have tested with latest version of websocket library (0.57.0).  Is this bug?

**Comment by engn33r** [comment]
I have two requests to gather a bit more information here before I dig deeper on this:
1. Could you [enable logging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and post the full error trace here?
2. Did you install this library from pip, or are you using the latest version from the master branch installed with `python setup.py install`? Both currently have the 0.57.0 version number (confusing, I know), so I would suggest uninstalling your current version and installing the latest master branch to see if that resolves the issue. It is possible that one of the most recent commits from 5 days ago, 3112b7d, modified some callback code and fixed this issue. The same callback code is mentioned in #467, which has a similar error to what you're seeing.

**Comment by the-anonymous009** [comment]
1. This is full log after enabling logging.
![image](https://user-images.githubusercontent.com/48025074/108578386-c93c5e80-7365-11eb-98b6-252746dd1007.png)
2. I installed this library from pip. I also test with version since 0.52.0, but all versions of 0.53.0 ~ 0.57.0 produce same error while 0.52.0 is file.  I also tested by installing latest master branch with ``` python setup.py``` and it resolves the issue.

**Comment by the-anonymous009** [comment]
![image](https://user-images.githubusercontent.com/48025074/108578666-a6f71080-7366-11eb-9b56-239e7cc7c1f9.png)

**Comment by engn33r** [comment]
I did not see this error before when installing from pip, but maybe because my code did not use the callback function in the same way as you. There are [many other callback-related issues](https://github.com/websocket-client/websocket-client/issues?q=is%3Aissue+callback) that I hope commit 3112b7d will fix. I will plan to make a new release soon so that installing the latest version will fix this error.

I will close this issue for now because it sounds like installing the latest master branch fixed the error, but if you encounter more problems, you can add additional information and we can reopen the issue.
