### ISSUE TITLE
Interpreter errors are mostly masked (no contexte)

### ISSUE THREAD

**Issue by projenix** [websocket-client/websocket-client#666]
Hello,

When an error happens inside a handler/thread the context is always lost (line number, stack trace, .. etc), I just get the basic error description with zero context to locate it.

How do you fix this problem?

Thanks in advance,

**Comment by engn33r** [comment]
It would help if you could give some additional context around the issue you're asking about. Could you [enable the debug trace feature](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and share your connection trace along with the error message? I will have a better idea of what you're encountering with this additional information. Another idea: if you installed websocket-client through pip and not from the latest github master source, try the latest master code because it should have fixed some callback problems since release 0.57.0.

**Comment by projenix** [comment]
tracewebsocket.enableTrace(True) looks to be the solution to my problem, I will test it asap and return if I have any more questions.

Thank you very much,

**Comment by engn33r** [comment]
Great, I am glad that solves it. I will close the issue for now because I assume this is solved, but if you add some updates we can reopen the issue later.
