### ISSUE TITLE
Callbacks fail when they are methods

### ISSUE THREAD

**Issue by quantotto** [websocket-client/websocket-client#667]
In the 0.58.0 release, websocket-client changed the way it handles callbacks, such as on_open, on_message.

Callbacks that are methods of a class are not supported now. Previously, there was a check in _app.py:
```
 def _callback(self, callback, *args):
        if callback:
            try:
                if inspect.ismethod(callback):
                    callback(*args)
                else:
                    callback(self, *args)

```
Now, starting from 0.58.0, it simply calls `callback(*args)` unconditionally.

Is there any reason for this change and does it mean that websocket-client drops support for method callbacks intentionally.

Thanks!

**Comment by quantotto** [comment]
Thank you for the details. I guess I didn’t search the history enough, just looked at issues filed in 2021.

Such a change breaks some interface compatibility and I thought this would be in a major (1.x release), but I understand that it reverts some other major changes.

Meanwhile, I have to revert to 0.57.0. As for PR, I have nothing to suggest at the moment as it would take time to digest  / outline design requirements and various use cases.

**Comment by engn33r** [comment]
I don't disagree with what you've said. This callback function has been a messy topic in the past, and arguably the introduction of it should have been the 1.x release and the reversion the 2.x release. Proper semantic versioning has been lacking in this project and I'll aim to improve that going forward. I'll consider this particular issue resolved for the moment since we have identified the root cause, but we can continue the discussion if I left something out.

As mentioned, the inheritance introduced by PR #442 could be a useful feature to add if someone wants to attempt an implementation that can avoid the pitfalls observed previously.
