### ISSUE TITLE
stop accepting messages, but does not close

### ISSUE THREAD

**Issue by progLks** [websocket-client/websocket-client#674]
Dear Author,

I have a strange situation - when I use binance websocket data stream, websocket is connected, everything is good, but sometimers, it can be once a day or once a month, i can ping and get pong, but i can't get messages. I'm very sorry if this situation is not related to you.
However, if you at least share your thoughts about this, I will be very grateful to you

**Comment by engn33r** [comment]
Please follow the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). More information will be needed to provide help. If the issue is intermittent and cannot be recreated easily, it is unlikely to be easily resolved.

**Comment by engn33r** [comment]
If you search old issues for the word "binance", you will find some example code that should get you started on a solution.
