### ISSUE TITLE
WebsocketApp on_close not dispatching close code or reason

### ISSUE THREAD

**Issue by elderlabs** [websocket-client/websocket-client#686]
As a continuation of #479 and #480, the library I'm working with defines that a wsApp should return a status code and a reason in some if not most cases. The problem here's that they've never returned on connection close, and I'm attempting to track why wsApp's aren't properly closing (in some cases - described below) and reopening when on_close is called (possibly related to #592).

My source and the on_close method I'm calling is [here](https://github.com/elderlabs/BetterDisco/blob/staging/dooley/disco/gateway/client.py#L242), and I'm initializing/wrapping wsApp [here](https://github.com/elderlabs/BetterDisco/blob/staging/dooley/disco/util/websocket.py#L19). 

I don't see any documentation explaining how wsApp is meant to return status codes, but they'd be helpful in tracking the larger issue I'm facing -- which is our core router rebooting occasionally, leaving wsApp in a dead state, when it should instead be caught by my loop that attempts to reinit the connection (which works 99% of the time, other than in this specific scenario where it instead hangs).

This issue is more related to what's happening [here](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L259) in wsApp's source. There should be some return from either `teardown` or `close_frame` that I can capture in my `on_close` method, however, the source doesn't appear to actually return that information, or allow the passing of a variable to enable the return of that information. There are other non-descript closed commits and issues surrounding the matter, but I'm not sure they were actual fixes, unless downstream changes lead to the feature not working. I've read a few things surrounding `enableTrace` in the docs, but that doesn't do what this feature should without enabling full-on debug logging, which is not what I'm doing here.

I think that should sum it up nicely, through possibly incoherently.

Thank you.

**Comment by engn33r** [comment]
@elderlabs Thanks for giving more detail and creating a new issue for this. Though I did not expect it, this issue led me down a rabbit hole that uncovered a bug that may be the cause behind many of the remaining open issues on this project related to on_close callback issues (#534, #612, #452, etc.). Long story short, the current master and next release should have this issue fixed by commit c414127, but let me know if that is not the case. I even [added documentation examples](https://websocket-client.readthedocs.io/en/latest/examples.html#receiving-connection-close-status-codes) for using close status codes to make everyone's lives easier. I am including the long-winded explanation of the issue below only in case anyone in the future is interested in what the problem was, because this fix probably may resolve several other open issues too.

The issue was fully contained in the _app.py file. I started troubleshooting this issue by placing debug print statements near all the calls to the `teardown()` function, because the on_close callback is only located in the teardown() function. In theory the on_close callback should be providing the close status code. I found that the `_get_close_args()` function, which is in the `teardown()` function and is supposed to return the close status code that you are looking for, was completely broken! There was an if statement to check if the close_frame input had a length of 3, but because of the close_frame's data type, this is never the case, so the code to extract the status code was never reached. Because this function was so broken, I saw the debug print statements firing within the teardown function twice for the closing of a single connection. The first close would be called from the `read()` function and the second would be from the `except` section of the `run_forever()` try/except code. This led to some other strange behavior, which you can examine in the older code, but things looks like they are working much better with the latest edits.

Before today, the `_get_close_args()` function hadn't been meaningfully modified in 6 years, so I can't say when exactly this issue first showed up (I have only been maintaining this project since January 2021). To solve the issue, I rewrote the `_get_close_args()` function to fix the logic and make it more readable, clarified variable names, added unit tests around this code, and documented how to receive close status codes from the server.

**Comment by elderlabs** [comment]
I'd blame the issue on upstream deps, like changes in Python3, unless the function never truly worked; whose to say!?

Thank you for the time and effort you put into this one, I, along with many others, am grateful for it and will test the changes myself shortly. Your dedication to this project is commendable and does not go unnoticed. What you noted above was a decent read, and interesting to say the least. I've seen "ghosts" like this myself with some projects, so it's refreshing to see that I'm both not alone, and that quick progress is being made on this project. I'm eager to see version 1.0.0, and wish you the best of luck continuing into the future.

Thanks again.

**Comment by garethsb** [comment]
The removal of the check `len(inspect.getfullargspec(self.on_close).args) != 3` caused a problem with an `on_close` handler defined without the additional arguments. I'm OK with this in a semver 1.0.0 breaking-API release, and we just had to add the `close_status` and `close_message` arguments to the handler, but I thought it was worth pointing out as it's not mentioned in the release notes.

**Comment by engn33r** [comment]
@garethsb if you could share a traceback you got for this problem and either a code example or explanation of the code that needed changing, that would be helpful in case other users have the same problem and encounter this issue.
