### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'

### ISSUE THREAD

**Issue by NickPintoG** [websocket-client/websocket-client#689]
Relevant snippet of code:

pip install websocket-client

import websocket

def on_open(ws):
blahblah

def on_close(ws):
blahblahblah

def on_message(ws,message):
blahblahblah

ws = websocket.WebSocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message)

ws.run_forever()

I receive the error **AttributeError: module 'websocket' has no attribute 'WebSocketApp'** on jupyter notebook which is weird, because i was running the exact same code on Google Colab and I was not receiving any errors on there.

I tried everything!! I tried doing what was suggested here: https://stackoverflow.com/questions/48730108/attributeerror-module-websocket-has-no-attribute-websocketapp-pip

I also tried this: https://stackoverflow.com/questions/42141689/attributeerror-module-object-has-no-attribute-websocketapp

I tried screwing around in my files and still no matter what I do I continue getting this error...

My python version is 3.8.3 btw.   Does anyone have a clue as to what is the problem here?

I will love you forever if you help me out,,, seriously... this been so annoying

**Comment by engn33r** [comment]
This is just a first guess, but I am going to speculate that this is an issue with your environment rather than this library. To try to give you a better answer, can you share the outputs of the following 4 commands?

`python3 -V`
`python2 -V`
`pip2 list | grep websocket`
`pip3 list | grep websocket`

If you want to run another test, try copying and pasting some of the [documentation examples](https://websocket-client.readthedocs.io/en/latest/examples.html) (especially the WebSocketApp ones) to see if they run or give an error.

**Comment by engn33r** [comment]
Can you give more information about where you are running this code? Is it in a jupyter notebook that you are hosting in a specific cloud provider? Or is it a jupyter notebook hosted by a specific third party website? If it is hosted by a specific website, can you provide the URL of the website?

How are you running your code? Are you using the command `python myfile.py`, are you using an interactive terminal (IDLE), or are you running the code directly from the jupyter notebook?

Try running these two other commands and sharing the output. The output may be long:
`pip list`
`pip3 list`

**Comment by NickPintoG** [comment]
![image](https://user-images.githubusercontent.com/83924049/117689737-11f6fd00-b188-11eb-9277-81f9e829c257.png)

I use the Anaconda Navigator to open the Jupyter notebook, and I am running the code directly from the notebook.

The two commands give the same output, as follows:

![image](https://user-images.githubusercontent.com/83924049/117690256-a3ff0580-b188-11eb-97d2-85656e4124c0.png)
![image](https://user-images.githubusercontent.com/83924049/117690579-00fabb80-b189-11eb-8951-efc066d39b21.png)
![image](https://user-images.githubusercontent.com/83924049/117690367-c5f88800-b188-11eb-93b4-74f3977874a3.png)

**Comment by engn33r** [comment]
I am now pretty certain this issue is outside the scope of this library and is an environment issue, which makes it hard for me to properly troubleshoot. I am not familiar with how this applications handles pip and PATH data. Wherever the code is getting run, somehow it does not use an environment or PATH variable that includes the location of the Python libraries you installed with pip like websocket-client. This sounds similar to issue #374.

I would prefer not to clutter the issue threads here with issues that aren't related to the websocket-client code, so while I will leave this issue open for a week or two if others want to try to help, I will close it after that time because it's not an issue with this project. Stack overflow or your local Python expert would be better places to get answers for this question because you have already mentioned your code works in a different environment.

**Comment by engn33r** [comment]
@samfux84 Try uninstalling `websocket` with `pip3 uninstall websocket`. I expect you should only need `websocket-client`.

Did you install the dependencies in [a virtual environment](https://docs.python.org/3/library/venv.html)? It does not appear so, I would recommend such an approach to avoid conflicts with other dependencies on the system.

When I installed this package and ran `import cell2location` like you did, I did not receive any error, only some warnings. I am using Python 3.10, not Python 3.11, and I recommend installing the latest websocket-client, version 1.6.1, instead of the older version you have installed. Although I received no warnings and the import worked as expected, the last warning I received was `/lib/python3.10/site-packages/umap/distances.py:1063: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
`

**Comment by samfux84** [comment]
@engn33r Thank you for your reply. I could finally resolve the issue by upgrading websocket-client from version 1.5.1 to 1.6.1 and now the error message is gone.
