### ISSUE TITLE
Send failed in Short-lived Connection

### ISSUE THREAD

**Issue by dinglei0719** [websocket-client/websocket-client#691]
Hi, 

I'm new in websocket and I write some code like this:

```
ws = create_connection("ws://*****/")
heart_dict = {'clientId': 'AAA', 'status': 'BBB', 'action': 'Heart'}
ws.send(json.dumps(heart_dict))
```

I test this code on 4 PCs (two with Win10 and the others with Win7).
Only one of the laptop with Win7 has the problem below:

The connection is OK, the "send" method does not get any error or exception.
But the server side does not receive anything.

I tried to close the firewall of the laptop but it doesn't work.

Is there any suggestion for me to locate the problem?

Thanks a lot

**Comment by engn33r** [comment]
Sorry, but if your code is working on other computers, then the issue is probably not with the websocket-client project and therefore this is a bit off topic. It is very hard to troubleshoot issues related to a specific system because they cannot be easily recreated. The only idea I have it to try uninstalling Python and reinstalling Python to update all the dependencies. If only a Windows 7 system has problems, it might be because the dependencies are old.

You could try running Wireshark to check if the Windows 7 system sent the message and the problem is that the message was not received, or whether the message is stuck in the Windows 7 system and was never sent.
