### ISSUE TITLE
Always match suffixes with NO_PROXY

### ISSUE THREAD

**Issue by pawamoy** [websocket-client/websocket-client#700]
The instructions copied from cURLin #671 seem to be in contradiction with the findings in this very interesting post: https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/

cURL apparently always strips leading dots from the values provided through NO_PROXY, as well as matches hostnames as suffixes (no exact match).

Since Python is doing the same, and is not case-sensitive regarding the *_proxy variables, I suggest websocket-client should support case-insensitive variables as well as always matching suffixes, allowing to disable the use of a proxy for both www.example.com and test.example.com when example.com is given in NO_PROXY.

A draft implementation:

```python
def _is_no_proxy_host(hostname, no_proxy):
    if not no_proxy:
        v = os.environ.get("no_proxy", os.environ.get("NO_PROXY", ""))
        if v:
            no_proxy = [part.strip().lstrip(".") for part in v.split(",")]
    if not no_proxy:
        no_proxy = DEFAULT_NO_PROXY_HOST
    if '*' in no_proxy:
        return True
    if hostname in no_proxy:
        return True
    if _is_ip_address(hostname):
        return any([_is_address_in_network(hostname, subnet) for subnet in no_proxy if _is_subnet_address(subnet)])
    for domain in no_proxy:
        if hostname.endswith("." + domain):
            return True
    return False
```

**Comment by engn33r** [comment]
@Codeglitches any comments on this? You are probably more informed on no_proxy than I am given your PR #671 contribution.

@pawamoy one nitpick I have with the line `os.environ.get("no_proxy", os.environ.get("NO_PROXY", ""))` is that I think it would not be truly case insensitive. For example, I need to check if it would catch an environment variable named "No_proxy" or "No_Proxy" or other strange capitalization cases. But I'll look at this further before any commits.

**Comment by Codeglitches** [comment]
You're issue is a little confusing, as you are discussing multiple issues. Let me try to break them down and correct me if I am wrong.

1) __websocket-client should support case-insensitive variables__
In stead of just looking for lowercase "no_proxy" it should also look for uppercase "NO_PROXY" if lowercase "no_proxy" is not found. You're code example does this. with the ```v = os.environ.get("no_proxy", os.environ.get("NO_PROXY", ""))``` line.
Which seems like a valid suggestion to me. However, to be consistent, this also means this should be implemented for "http_proxy" and "https_proxy". If we all agree, this should be an seperate issue, or the scope of this issue should be made to include it (by renaming the issue?).

2) __allow for whitespace in the no_proxy setting__
At least, that is what I get from your code (and the mentioned article), which is a good suggestion too. Again, something that should also be checked and implemented for "http_proxy" and "https_proxy"

3) __always matching suffixes__
The current implementation is that a "no_proxy" entry of ".example.com" (note the leading dot) will match "example.com", "www.example.com" and "test.example.com" and any other subdomain of "example.com". Just "example.com" will only match "example.com" not "www.example.com".

I think you're suggestion is that a no_proxy entry of "example.com" should match "www.example.com" and "test.example.com" too?

Implementing this, would make all hostnames an automatic 'domain' for which all subdomains will match. What I mean is "www.example.com" would match "www.example.com" and "1.www.example.com" and there is no way to just match "www.example.com" and not match "1.www.example.com". I guess that is why the leading dot was used; it allows an entry to be an exact match (no leading dot) or a domain suffix (with leading dot).

My personal thoughts on this are, to not implement this as it provides less flexibility.

As it is unclear to me what "python" does in this case, I decided to look the "requests" library; that at least is one of the leading python implementations, right?. In the `should_bypass_proxies` method of [utils.py](https://github.com/psf/requests/blob/c45a4dfe6bfc6017d4ea7e9f051d6cc30972b310/requests/utils.py) it seems however that they too match "example.com" to "www.example.com" as @pawamoy suggests. They don't even care to remove the leading dot.

This however, suggest, although I personally don't fully agree, @pawamoy suggestion is valid. And removing the leading dot makes it less likely to cause problems for current implementations.

However, we should note it breaks backward compatibilby for those corner cases when "www.example.com" currently does not match "1.www.example.com". I don't think many (if any) real world production environment depends on this feature because it is very unlikely different tools will implement this the same way.

**Comment by Codeglitches** [comment]
> @pawamoy one nitpick I have with the line `os.environ.get("no_proxy", os.environ.get("NO_PROXY", ""))` is that I don't think it would be truly case insensitive. For example, I need to check if it would catch an environment variable named "No_proxy" or "No_Proxy" or other strange capitalization cases. But I'll look at this further before any commits.

As far as I know no tool implements a truely case insensitive "no_proxy" environment variable as that "No_PrOxY" matches too. All issues are using "no_proxy" (all lower case) and "NO_PROXY" (all upper case). So I thinks @pawamoy line of code is fine.

**Comment by engn33r** [comment]
@Codeglitches I agree. After thinking about how to implement a truly case insensitive "no_proxy" environment variable, because os.environment does not have a built-in solution, I think any approach would add overhead that would not be sufficiently worthwhile for the benefit. It's better to require one of the two consistent capitalization approaches (for "http_proxy" and "https_proxy" too) and reduce overhead checking for rare cases.

I don't have strong opinions on the other points so I will let @pawamoy chime in.

**Comment by pawamoy** [comment]
@Codeglitches excellent write-up, thank you for your thoroughness.

The article I mentioned linked to the sources of urllib (in Python's standard lib) about [case-sensitiveness](https://github.com/python/cpython/blob/030a713183084594659aefd77b76fe30178e23c8/Lib/urllib/request.py#L2488-L2517) and [how it matches hosts](https://github.com/python/cpython/blob/030a713183084594659aefd77b76fe30178e23c8/Lib/urllib/request.py#L2519-L2551).

It was just a bit surprising to have a different behavior with websocket-client than with other tools I've used (and lead to some debugging time), but I can still configure my environment to work with both (lowercase no_proxy and leading dots), so if implementing this change is too much of a hassle (backward compatibility, etc.), I won't fight for it :slightly_smiling_face: 

Your decision @engn33r!

**Comment by engn33r** [comment]
I decided to implement suggestion 1 (uppercase and lowercase environment variables) and suggestion 2 (remove whitespace in environment variables). I did not implement suggestion 3 only because it seems like a trickier topic and this is the first thread that has mentioned it in this project. I'll leave things as is for now, but if someone else mentions this issue in the future, I will be happy to look more closely at the change in suggestion 3.

**Comment by pawamoy** [comment]
I think you misunderstood suggestion 2? From what I understand, the suggestion was to *keep* spaces in the comma-separated values of NO_PROXY, not to remove them from HTTP_PROXY and HTTPS_PROXY as well (although stripping them left and right for sure), which is what `replace` does. The code is now more consistent though.

**Comment by pawamoy** [comment]
Also, thanks for adding support for NO_PROXY, I greatly appreciate it :slightly_smiling_face:

**Comment by engn33r** [comment]
@pawamoy yes I think my comment about implementing your suggestion 2 is inaccurate - thanks for the correction. I only took the 2nd part of what Codeglitches said, `something that should also be checked and implemented for "http_proxy" and "https_proxy"` and maintained consistency with the existing `replace()` approach. Correct me if I'm wrong, but I don't see a scenario where whitespace matters much at this point in the code so it's probably fine as is.

**Comment by felix-last** [comment]
As I understand this ticket, matching suffixes should happen with all domains, not just those starting with a period. I found that the current code does not match `subdomain.domain.com` when `domain.com` is in no_proxy. Instead, `.domain.com` must be present in no_proxy.

See snippet from current master below:
https://github.com/websocket-client/websocket-client/blob/150df4faada4f9fc7db5bf1f15d7728e8a97088b/websocket/_url.py#L124-L126 

Any thoughts? Would provide a MR if needed.

**Comment by engn33r** [comment]
@felix-last the first post from @Codeglitches in this ticket, specifically item 3, describes how the current websocket-client implementation is more flexible so I think the current approach is reasonable. If you have encountered a specific situation where this is problematic, please share some more details about the incompatibility.

**Comment by felix-last** [comment]
@engn33r I must have overlooked Codeglitches' point 3. The argument makes sense to me, despite being inconsistent with other libraries.
