### ISSUE TITLE
Question regarding correct use of threading

### ISSUE THREAD

**Issue by RT-Tap** [websocket-client/websocket-client#705]
Hi, first off I want to thank everyone who contributes and maintains this library and say that I really appreciate it.
So I'm writing  a pretty simple application that uses threading and I have no issues per se BUT when I was running the application I wanted to make sure all my threads were handled correctly and exit correctly, this is when I realized that the implementation of `run.for_ever()` in this library creates a thread and that thread doesnt exit on_close.
I think it may be easier to describe whats going on if I show some code and explain from there, so using the following:

```python
ws = websocket.WebSocketApp(uriEndpoint, on_message=on_message, on_error=on_error, on_close=on_close)
print(f"active threads before run_forever : {threading.active_count()}")

listeningForMessages = threading.Thread(target = ws.run_forever, kwargs={'ping_interval':300, 'ping_timeout':1, 'ping_payload':'pong'})
listeningForMessages.daemon = True
lissteningForMessages.start()
print(f"active threads after starting run_forever : {threading.active_count()}")

time.sleep(1)
print(f"active threads after sleep : {threading.active_count()}")

doSomethingElse = threading.Thread(target= somethingElse)
doSomethingElse.daemon = True
doSomethingElse.start()
print(f"active threads after adding somethingElse : {threading.active_count()}")

doSomethingElse.join()
print(f"active threads after joining somethingElse : {threading.active_count()}")

ws.close()
listeningForMessages.join()
time.sleep(2)
print(f"active threads after joining listeningForMessages : {threading.active_count()}")
```

the sleep functions are there to allow the thread to finish (as demonstrated necessary by the print before and after the first sleep call).  Anyway the output looks like this:
active threads before run_forever :  1
active threads after starting run_forever : 2
active threads after sleep :  3
active threads after adding somethingElse :  4
active threads after joining somethingElse : 3
active threads after joining listeningForMessages : 3

so based off of the output, 
first print: makes sense - before we start any additional threads we only have the original main thread 
second print: makes sense - we create another thread with threading.Thread and start it so should have 2
third print: where did this extra thread come from? I assume the `ws.run_forever()` call creates a thread in the background to handle incoming messages but not really worrying  
fourth print: makes sense assuming that our previous assumptions about `ws.run_forever()` is true this also makes sense because were running another thread on top
fifth print: makes sense - were waiting for our most recent thread to finish and it does
6th print: doesnt seem right - ideally this should be 1 but the fact that its 3 is kind of worrying because it shows that neither the thread I called directly to start run_forever() neither the thread created by running run_forever finishes, no matter how long you wait.

So my question is, does this even matter? Should I be worried?  Is there anyway I can close out the threads created by starting run_forever?

**Comment by engn33r** [comment]
First, I modified your code to make a complete and contained example that can run on any computer. I have shared the code below.

Second, the extra thread from `ws.run_forever()` is because an extra thread is created to manage the websocket ping/pong timeout. If you remove the kargs from `ws.run_forever()`, the extra thread disappears.

Finally, when I run the example file below, I sometimes see the program end with 1 active thread and sometimes with 2 active threads. I will attempt to dig deeper using the [trace library](https://docs.python.org/3/library/trace.html), but I don't know if I will find a fix in the next few weeks. At first glance, this may be related to the dispatcher issue in #452. In the meantime, I would like input from others if you are able to replicate this strange behavior of observing the program end with both 1 and 2 threads after running the example below over 20 times. If you only observe the program completing consistently with either 1 or 2 threads remaining, this would also be interesting to know.

```python
import websocket
import threading
import time

def on_message(wsapp, message):
    pass
    # print(message)

def on_error(wsapp, err):
    print(err)

def on_close(wsapp, close_status_code, close_msg):
    print("on_close args:")
    if close_status_code or close_msg:
        print("close status code: " + str(close_status_code))
        print("close message: " + str(close_msg))

def ws_run_forever(ws):
  ws.run_forever(ping_interval=300, ping_timeout=1, ping_payload="pong")

ws = websocket.WebSocketApp("wss://stream.meetup.com/2/rsvps", on_message=on_message, on_error=on_error, on_close=on_close)
print(f"active threads before run_forever: {threading.active_count()}")

#listeningForMessages = threading.Thread(target=ws_run_forever(ws))
listeningForMessages = threading.Thread(target = ws.run_forever, kwargs={'ping_interval':300, 'ping_timeout':10, 'ping_payload':'pong'})
listeningForMessages.daemon = True
listeningForMessages.start()
print(f"active threads after starting run_forever: {threading.active_count()}")

time.sleep(1)
print(f"active threads after sleep : {threading.active_count()}")

print(f"Going to close websocket now")
ws.close()
listeningForMessages.join()
time.sleep(2)
print(f"active threads after joining listeningForMessages: {threading.active_count()}")
```

**Comment by RT-Tap** [comment]
Hey sorry I couldn't get back to you earlier.

I ran your code and received 1 active thread at the end after running 28 times, so it does seem to join correctly on my end.

After looking into my code more carefully and debugging it turns out another library I was using creates 2 additional threads that I had not expected and accounted for previously so I think everything from this library cleans up nicely, at least on my end.  I will have to figure out how to join/clean the threads from that library separately.

Should I close the topic or see if I can replicate the issue you described?

Off topic - I do want to ask you a question about handling ping/pongs (or more specifically how this library handles it) as I'm not very familiar with the websockets protocol standard.  Is having a method defined for on_ping when creating the websocket object the the same as automating ping responses by adding arguments to run_forever method?  For example let's say the server sends a ping to all clients every 10 minutes to verify they are still listening and expects a 'pong' response.  Is it redundant to have an on_ping method defined as well as having the library automate this with the run_forever method (and the correct arguments)?  Also just to verify the run_forever method can either automatically respond to a ping or send unsolicited pong's every so often correct?  The "best" way to handle this (from my perspective and opinion) would be to send unsolicited "pongs"  every 5 minutes (and again this can be done from the run_forever method correct?), is that safe to assume?

**Comment by engn33r** [comment]
Great, I'm glad the threading issue was resolved. I may have observed that strange threading behavior while testing on a VM with unreliable networking, because I can't duplicate the issue now on a different system. I will close this issue because the original threading issue is resolved, but we can continue discussing the ping/pong question here.

I think the shortest answer I can give to your ping/pong question is to point you to [the ping/pong example in the docs](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage). The WebSocketApp ping/pong example should resolve things. `on_ping` and `on_pong` allow you to trigger custom actions when a ping or a pong is received by websocket-client. However, if websocket-client receives a ping from the server, it will automatically reply with a pong because that is specific by the official websocket RFC6455. If you try to perform this action manually, it would be redundant. If you want to use the built-in customization options, you can use the WebSocketApp parameters `ping_interval`, `ping_timeout`, and `ping_payload` to customize the ping messages sent from the client to the server.

If that doesn't answer things, we can continue the conversation here even though I closed the issue.
