### ISSUE TITLE
run_forever continual rebuild is ssl import fails

### ISSUE THREAD

**Issue by sandpointhydro** [websocket-client/websocket-client#711]
Bug in create_dispatcher in run_forever definition causes socket to continually destroy and rebuild if ssl import fails.

_ssl_compat.py sets `ssl = None` if ssl import fails

This code from _core.py:
```python
def is_ssl():
    return isinstance(self.sock, ssl.SSLSocket)
```
will raise AttributeError if ssl is None.

`create_dispatcher()` in _app.py will then fail inside try/except loop, causing rebuild of ws.

-----
propose changing _core.py to:
```python
def is_ssl(self):
    try:
        return isinstance(self.sock, ssl.SSLSocket)
    except:
        return False
```

or changing _ssl_compat to return an object with an SSLSocket attribute set to None

**Comment by engn33r** [comment]
To get a better understand of the issue here, can you share:
1. What version of Python 3 you are using (the output of `python3 -V`, because only Python3 is current supported by websocket-client)
2. What version of websocket-client you are using (the output of `pip3 list | grep websocket`)
3. What version of OpenSSL you are using (The output of `openssl version`)
4. What version of pyOpenSSL you are using (The output of `pip3 list | grep -i ssl`)
5. Are you using websocket-client on a standard computer/server, or a limited system (such as an embedded system)? I am wondering why the `import ssl` is failing

**Comment by engn33r** [comment]
Thanks for sharing your suggested fix. Let me know if you encounter issues with the latest commit.
