### ISSUE TITLE
How to send a message to a custom event (emit)

### ISSUE THREAD

**Issue by evecimar** [websocket-client/websocket-client#716]
When we use the send() method to send a message to the server, this message is sent and received at the server in the event message. I would like to send a message to the server and it arrives in a custom "channel", such as 'sales'.
In some studies I contacted that I should emit a new event, which is usually using the emit('name_of_event', 'message') method, but I can't find the emit() method.

**Comment by engn33r** [comment]
It sounds like you are using socket.io, which is a protocol that often uses websockets. I would recommend using the [python-socketio project](https://github.com/miguelgrinberg/python-socketio/) instead of this one. If I am mistaken, then please explain how these channels are handled on the server, because they are not a default feature of the websocket protocol.
