### ISSUE TITLE
Document `WebSocket.send_binary` method?

### ISSUE THREAD

**Issue by benhoyt** [websocket-client/websocket-client#736]
The `WebSocket` class has a handy `send_binary()` method, however, it doesn't have a docstring and doesn't appear in the documentation, so I wasn't sure whether it was supposed to be part of the public API or not. (Though I notice there's at least one test for it.)

We should add a docstring either way, either to say "yes, here's what it does, use it" or "here's what it does, but it's deprecated, use `send(x, opcode=websocket.ABNF.OPCODE_BINARY)` instead".

I'm happy to submit a PR to add the docstring once I know which direction you want to go.

**Comment by engn33r** [comment]
I don't have any immediate thoughts because I haven't used the `send_binary()` function in my projects, but it does appear in [a unit test](https://github.com/websocket-client/websocket-client/blob/5f32b3c0cfb836c016ad2a5f6caeff2978a6a16f/websocket/tests/test_websocket.py#L186). I would lean towards `send_binary()` not being deprecated but just infrequently used, unless you see something indicating otherwise.

**Comment by benhoyt** [comment]
I did a quick of some open source code [using SourceGraph](https://sourcegraph.com/search?q=context:global+ws%5C.send_binary%5C%28.*%5C%29+lang:python&patternType=regexp), and several of the references are using the `websocket` library and call this `send_binary` method, so I think it's safe to say usage of it is out there in the wild. Might as well add a docstring! :-)
