### ISSUE TITLE
On_message handling for high volume stream

### ISSUE THREAD

**Issue by Spino1981** [websocket-client/websocket-client#740]
Apologies, this is not an issue but rather a clarification request.
I have looked in the documentation and I couldn't find an answer.

I would like to ask how a high volume of incoming data to the websocket client is handled by the on_message event.
I understand that the function linked to the on_message event is triggered every time a new message is received from the server. What happens if/when a high volume of messages is received and the on_message function takes some time to handle the data?
Are the "on_message" queued and executed once there are free resources?

Thank you in advance

**Comment by engn33r** [comment]
I don't have an exact answer about `on_message`, but a similar question about high volume WebSockets was recently asked in #735. You can always use the [Python trace](https://docs.python.org/3/library/trace.html) tool to examine the details of a particular piece of code, since most of the project's documentation attempts to remain high level.

If you are encountering specific issues with your program, please share details as outlined in the [contribution guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).
