### ISSUE TITLE
When the websocket object is initialized, it supports the incoming ssl_context = ssl.sslcontext, right?

### ISSUE THREAD

**Issue by reynaldliu** [websocket-client/websocket-client#743]
When the websocket object is initialized, it supports the incoming ssl_context = ssl.SSLContext, right?

ssl_context

```
  def __init__(self, get_mask_key=None, sockopt=None, sslopt=None,
                 fire_cont_frame=False, enable_multithread=True,
                 skip_utf8_validation=False,ssl_context=None, **_):
        """
```

```
def _wrap_sni_socket(sock, sslopt, hostname, check_hostname,  ssl_context):
    # my add code 
     if ssl_context:
            context = ssl_context
     else:
            context = ssl.SSLContext(sslopt.get('ssl_version', ssl.PROTOCOL_TLS))

```

**Comment by engn33r** [comment]
The `__init__` code you shared above includes a `ssl_context` parameter, which is not in the websocket-client code and is not the suggested way to use SSLContext. SSLContext parameters should be set using sslopt. See [this FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#what-else-can-i-do-with-sslopts) for a list of SSLContext parameters and [this FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html?highlight=sslopt#how-to-disable-ssl-cert-verification) for an example of using sslopt.

**Comment by engn33r** [comment]
If I understand correctly, you are looking for additional functionality to be added to websocket-client for an unusual edge case that you are trying to solve. It is generally best to handle these in your custom application rather than a common library, but if you see a simple way to integrate this feature into websocket-client, you can submit a PR as [described in the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).
