### ISSUE TITLE
websocket/_app.py Line 412 doesn't need to pass in self?

### ISSUE THREAD

**Issue by PeterTranHuynh** [websocket-client/websocket-client#755]
* Python Version: 3.9.6
* Environment: RHEL 7.9

I was using this library for a project and ran into a peculiar issue with syntax in python 3.9.6. Below is a snippet of the issue I ran into.

To resolve this, I simply removed the `self` passed into `self.on_error(self, e)`. 

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PATH/TO/HOME/.local/lib/python3.9/site-packages/websocket/_app.py", line 407, in _callback
    callback(self, *args)
TypeError: on_error() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/python-3.9.6/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/python/python-3.9.6/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/PATH/TO/HOME/.local/lib/python3.9/site-packages/websocket/_app.py", line 371, in run_forever
    self._callback(self.on_error, e)
  File "/PATH/TO/HOME/.local/lib/python3.9/site-packages/websocket/_app.py", line 412, in _callback
    self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given
```
It looks like this particular block inside `_callback` isn't within the code coverage, so it may have been missed?

**Comment by engn33r** [comment]
This modification looks reasonable to me, and it obviously solved the issue you encountered. It would be helpful if you want to share a block of code that triggers this code that could be used to create a test to increase code coverage, otherwise I'll look at writing such a test later so that this code gets tested before the "self" parameter is removed.

**Comment by j-a-n** [comment]
I wrote a test for this code in #862 
The on_error callback receives the WebSocketApp instance as first argument and the Exception instance as second argument.
So the code looks correct to me.
What does your on_error callback function looks like?

**Comment by engn33r** [comment]
I agree with @j-a-n, because the on_error callback function is not defined in the library, this error is highly dependent on how you implemented the callback. The error you got may be because you did not define the on_error callback inside of a class.

I am closing this because as best as I can tell, it's not an issue with the code in this repository.
