### ISSUE TITLE
very slow connection time when using localhost ws

### ISSUE THREAD

**Issue by sancelot** [websocket-client/websocket-client#773]
Hi,
I found this problem on my windows 10 machine, when trying to connect a socket using 
eg ws://localhost:6003, the connect time was almost 2seconds !
when using ws://127.0.0.1:6003 it connects immediately

I found the issue was coming from addrinfo_list generated by 
https://github.com/websocket-client/websocket-client/blob/master/websocket/_http.py#L122
That takes some time when used in _open_socket()

using localhost, the list is :
[(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 6003, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 6003))]        

using 127.0.0.1 adress this list is :
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 6003))]

**Comment by engn33r** [comment]
This does not look like a websocket-client issue. From what you shared, your localhost domain resolves to both IPv6 and IPv4. Your websocket server is probably running on IPv4, which is 127.0.0.1, but the order of IPs for localhost has the IPv6 address, ::1, as the first IP in the list. So websocket-client tries to connect to the IPv6 localhost, the connection times out because the server is on IPv4, and when the connection is tried again on the IPv4 address it succeeds.
