### ISSUE TITLE
Connection errors on send() are not caught, and the ws is not tagged as closed

### ISSUE THREAD

**Issue by aathan** [websocket-client/websocket-client#776]
As far as I can tell, the low level socket `def send()` in _socket.py does not catch `OSError` and therefore does not catch things like `BrokenPipeError`. Looking at the call stack for `def send()` defined in _core.py which ultimately uses send() it also catches nothing.

This creates the situation that you must catch these errors when you send() and externally close() the websocket yourself.

Is that intended? If so, it deserves mention in the documentation.

**Comment by engn33r** [comment]
That is not intended. Would you be able to create a PR?

I don't know if you're on Windows but I do see there's a comment that mentions triggering OSError in Windows in _http.py: https://github.com/websocket-client/websocket-client/blob/81fa70d259ce1609b3fb1bf66c8a9bed81a3f28c/websocket/_http.py#L153

**Comment by aathan** [comment]
If I’m right: Just connect to any server and forcibly close the far side then send(). You should get a raise that at your callsiteninstead of it being caught and handled in websocket code, and the connection will probably still be open. As a user if the library, your workaround would be to manually call close() in your exception handler.

All I can do for now is file this observation. You should probably draw your own conclusions from the source. My bug report is on the basis of a quick read of the code after observing high level behavior consistent with my analysis in an app that ises websocket.

A.

**Comment by aathan** [comment]
I don’t think the line you linked to is relevant.

**Comment by engn33r** [comment]
Ah, so both of us were just glancing at the code briefly. I will try to explain on a deeper level then.

If you aren't experiencing any particular issues, I expect the code is working as it should since I don't recall past issues around this exact functionality. How websocket-client performs when the server closes the connection depends on whether you are using a short-lived connection or a long-lived connection with `run_forever()`. If you are using a short-lived connection, then the closing of the connection should be handled manually. For reference, most of the short-lived examples in the documentation include a call to `close()`. If you want to submit a PR to add `close()` to the other short-lived examples, that would be great. In contrast, if a long-lived connection is used and a dispatcher is set, then a server can disconnect, go offline, get back online, and restart the connection without the user having to do anything.

If you are experiencing an issue with a particular edge case, please [share the details of it](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). For now I'll assume the question has been resolved.

**Comment by aathan** [comment]
I'm not sure you understand what I'm reporting.

The examples you reference are calling `ws.close()` in order to close the websocket under normal operating conditions, because the program is finished. What I am reporting, which is also not handled by the "long lived" WebSocketApp (as far as I can tell from a quick code review), is that exceptions raised by the low-level read/write calls on the network socket are not caught by the websocket code, and do not change the state of the websocket to reflect the implicit state of the underlying socket given those execptions were raised.

For example, if you do:

```
try:
     ws.send()
except OSError:
    print(ws.connected)
```
and the far side drops the connection before your send(), you will get a `BrokenPipeError` raised and ws.connected remains True. In fact, the websocket is dead/disconnected. The far side has closed the socket. By "drops the connection" I mean a dropped TCP socket not a graceful websocket close w/ websocket handshaking.

I don't claim to be fully informed about the internals of the websocket RFC/protocol. Maybe semantically the connection could still be open and re-started via a reconnection to the far side, and therefore it is correct that ws.connected==True immediately following a BrokenPipeEror; but I doubt it.

Generally, it looks like the websocket code simply punts on dealing with low level connection/read/write errors.

Arguably, instead, the websocket code should catch low level exceptions and do the necessary cleanup and signaling. It does not. Users of websocket must therefore know to catch these errors and manually call the necessary cleanups (such as calling close() to mark the websocket as closed).

I don't have time to review the documentation, but all this is not mentioned therein, it should be; and I wanted to bring it to your attention. Good networking code should catch exceptions, and it should therefore note that it is the user's responsibility to catch low level read/write/connection exceptions and call the websocket methods necessary to perform any implied cleanups.

Probably, for many errors, the websocket instance can just be thrown away. However, in many programs, you'll have code that checks things like `ws.connected` to see if it should reconnect to a server etc. Since this flag is not set False on closed low level socket errors, such code won't notice.

Finally, to answer your question, yes: I observed this behavior in some code that uses websocket. The code incorrectly assumed that after certain types of exceptions, the websocket would already know it was closed without having to manually call close().
