### ISSUE TITLE
BUG 处理超40秒以上任务   强迫关闭

### ISSUE THREAD

**Issue by wuqiang-001** [websocket-client/websocket-client#794]
![image](https://user-images.githubusercontent.com/85499933/153546860-3ee2d04d-2f1a-440d-a050-dad209995f49.png)

**Comment by engn33r** [comment]
This looks similar to #678. I did not have a good solution because this might be an issue outside of websocket-client. My guess is the connection is closed unexpectedly. If you want to connection to stay open, use the [long life connection example in the README](https://github.com/websocket-client/websocket-client#long-lived-connection).
