### ISSUE TITLE
Support for HTTPS proxies?

### ISSUE THREAD

**Issue by ecbftw** [websocket-client/websocket-client#796]
Hello!  I'm just getting familiar with your library and so far I'm really impressed with how well it is documented and how easy it was to replace a legacy implementation.  (Old version was based on tornado. Besides tornado's websocket client being far less mature overall, my immediate need was to add proxy support to my websocket connections, which tornado doesn't have.)

In any case, I'm curious if there are plans to add support for HTTPS-based CONNECT proxies?  I realize CONNECT allows for end-to-end encryption and certificate validation of the websocket session itself, so it may not seem necessary at first to encrypt the first hop to the proxy, but if that proxy requires authentication, then those credentials would not be encrypted and could be exposed.  For this reason, I anticipate some of my users may have commercial security proxy appliances in place that require HTTPS.

While there isn't explicit support now, I had considered experimenting with wrapping my own socket with TLS and then passing it in during connect(), but I wasn't sure if this would actually work in the specific case of using a proxy.  Thoughts?  

Of course point me to any threads discussing this already.  I did search around for it here and on the web generally, but my keywords didn't turn up any relevant discussions. 

Thanks!

**Comment by engn33r** [comment]
While using a HTTPS proxy instead of a HTTP proxy sounds reasonable at first glance, I don't think this is how it is done in practice: https://stackoverflow.com/questions/24218058/python-https-proxy-tunnelling#answer-24229123

If you use a HTTPS proxy to the proxy server, you are allowing the proxy server to decrypt the communications before they are sent to the actual destination. This design effectively enables a man-in-the-middle attack.

I am not an expert on proxy configurations in corporate environments, so if you can point out a Python library that supports HTTPS proxy connections for the use case you described, it might be a feature to consider in the future. The last major code change related to proxy support was fbcbd43, which replaced PySocks with [python-socks](https://github.com/romis2012/python-socks) for SOCKS4 and SOCKS5 proxy connections. PySocks and python-socks only support HTTP proxies, not HTTPS proxies.
