### ISSUE TITLE
Using multithreading in websocket, one of the thread's priority is higher?

### ISSUE THREAD

**Issue by zevcc-gh** [websocket-client/websocket-client#801]
I have written a python script for doing some testing on my server.
I want to record the time needed between request and response.  
In my script, I created a thread to keep calling an endpoint at a certain rate.
And the main thread is for listening to the response.

If I set a high calling rate, the recorded time will keep increasing.
From my observation, it looks like the listening thread getting "slower" than usual.
I'm sure that the server-side has no problem.

I cannot post my full script here. Here is some code that I hope helps you to understand my problem.

```
#called in another thread, it wont block the listening thread
def create_something(ws):
    while True:
        thread_pool_create.submit(...) #create a unique request id and record each request time
        time.sleep(1) #normal rate, the recorded time is only 0.05s
        #time.sleep(0.1) #abnormal rate, the recorded time keep increasing

def on_create_something(ws, res):
    cal_time(res['id']) #calculate the time
```

**Comment by engn33r** [comment]
If possible, I would suggest using a special websocket load testing tool rather than creating your own.

If you encountered a specific error message from websocket-client, please share it. If there is no error, the issue might be coming from the logic in your code, which is not easy to solve without seeing the full code. You may find some solutions in our [threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html).
