### ISSUE TITLE
How to set timeout with dispatcher?

### ISSUE THREAD

**Issue by zevcc-gh** [websocket-client/websocket-client#803]
I need to implement reconnect feature for my app. so I follow the instruction to use dispatcher in my script.
Also I need to maintain my timeout feature , but the dispatcher is keep looping itself. the code cannot go to the next line.
Can you guide me how to add timeout if i added dispatcher?

```
if __name__ == "__main__":
    TIMEOUT = 100
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://api.gemini.com/v1/marketdata/BTCUSD",
                              on_open=on_open,
                              on_message=on_message,
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever(dispatcher=rel)  # Set dispatcher to automatic reconnection
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch() # self looping here, cannot go to the next line
    time.sleep(TIMEOUT)
    ws.close()
```

**Comment by engn33r** [comment]
The code you shared is not using the websocket-client timeout feature, and because you do not set a timeout and use `run_forever`, the code will never timeout. [Follow the documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-timeout-value) to set a timeout value for the websocket.
