### ISSUE TITLE
Trying to make WebSocket connection over HTTP type of proxy.

### ISSUE THREAD

**Issue by gaproof** [websocket-client/websocket-client#812]
Hey, I'm trying to connect with websocket server using http proxy.

`self.socket = websocket.create_connection("secret", http_proxy_auth=("secret", "secret"), http_proxy_host="secret", http_proxy_port="secret",proxy_type="http", enable_multithread=True )`

But when I try to run it, connection is instantly closed.
Any ideas why? I don't really know websockets protocol good.

**Comment by engn33r** [comment]
I will need some more information to provide any help. What http proxy software are you using? Can you share a [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options)? Have you used websocket-client to connect to a public endpoint without a proxy using [one of the examples with public URLs](https://websocket-client.readthedocs.io/en/latest/examples.html) to make sure you understand how a connection should work? Did you review the [proxy help documentation](https://websocket-client.readthedocs.io/en/latest/examples.html)?

**Comment by gaproof** [comment]
> 

I'm not using a proxy software. It's a http/s proxy which I bought from a provider. When i use local proxy to intercept packets everything is working fine. 

This is my debug trace:
`Connecting proxy...
--- request header ---
CONNECT server.6obcy.pl:7004 HTTP/1.1
Host: server.6obcy.pl:7004
Proxy-Authorization: Basic secret


-----------------------
--- response header ---
HTTP/1.1 200 Connection Established
Proxy-agent: Proxy
-----------------------
--- request header ---
GET /6eio/?EIO=3&transport=websocket HTTP/1.1
Upgrade: websocket
Host: server.6obcy.pl:7004
Origin: https://server.6obcy.pl:7004
Sec-WebSocket-Key: 
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: r8WMxHC0EIFsmlU3dmkutgmuMOM=
Sec-WebSocket-Version: 13
WebSocket-Server: uWebSockets
-----------------------
++Sent raw: b'\x81\xfa\x02\x13\xf9\xfc6h\xdb\x99tL\x97\x9dov\xdb\xc6"1\xa6\x8fc`\xdb\xd0"1\x9c\x8a]w\x98\x88c1\xc3\xdcy1\x9a\x94c}\x97\x99n1\xc3\xdc ~\x98\x95l1\xd5\xdc ~\x80\x8fg\x7f\x9f\xde83\x82\xdeqv\x81\xde83\xc9\xd0"1\x95\x93a1\xc3\xdc3!\x84\xd0"1\x89\x8egu\x9c\x8eg}\x9a\x99q1\xc3\xdcy1\x8a\x99z1\xc3\xdc2?\xd9\xden|\x9a\xde83\xca\x81\x7fn'
++Sent decoded: fin=1 opcode=1 data=b'4{"ev_name": "_sas", "ev_data": {"channel": "main", "myself": {"sex": 0, "loc": 12}, "preferences": {"sex": 0, "loc": 3}}}'
++Rcv raw: b'\x81Q0{"sid":"X1EceWuJLBxCLuy","upgrades":[],"pingInterval":25000,"pingTimeout":40000}'
++Rcv decoded: fin=1 opcode=1 data=b'0{"sid":"X1EceWuJLBxCLuy","upgrades":[],"pingInterval":25000,"pingTimeout":40000}'
++Rcv raw: b'\x81b4{"ev_name":"cn_acc","ev_data":{"conn_id":"X1EceWuJLBxCLuy","hash":"174#114#114#108","tlce":null}}'
++Rcv decoded: fin=1 opcode=1 data=b'4{"ev_name":"cn_acc","ev_data":{"conn_id":"X1EceWuJLBxCLuy","hash":"174#114#114#108","tlce":null}}'
++Rcv raw: b'\x88\x00'
++Rcv decoded: fin=1 opcode=8 data=b''
++Sent raw: b'\x88\x82D\xa5F\xa5GM'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
Connection to remote host was lost.`

**Comment by engn33r** [comment]
If you don't have control over the proxy then there might not be much that we can do, especially if the connection works fine without the proxy. Some observations from this data:
1. The "sid" value indicates this is probably a [socket.io](https://github.com/socketio/socket.io) connection, which is a protocol built on top of websockets. The websocket-client library is usually used with plain websockets. If the API documentation indicates this protocol is used, consider using [another library](https://github.com/miguelgrinberg/python-socketio/) to see if it maintains the connection with the proxy in place.
2. The "Connection to remote host was lost" might mean the proxy dropped the websocket connection entirely after the first request/response, which is very possible if you are using a third party because they might want to protect against [proxy bypass attack vectors](https://github.com/PalindromeLabs/awesome-websocket-security#reverse-proxy-bypass-using-upgrade-header). Try testing several of the [examples with public endpoints](https://websocket-client.readthedocs.io/en/latest/examples.html) using the proxy to see if the connection still drops after one request/response. If the same problem exists on several public endpoints, your proxy provider is causing the issue.
