### ISSUE TITLE
on_message question

### ISSUE THREAD

**Issue by mccoydj1** [websocket-client/websocket-client#814]
Is there any way to make on_message concurrent executions? so they will fire on new messages regardless if the old message is processed or not? This is my code - it delivers a new message every 4 seconds but that is because it has to wait for the old message to get done

```
import websocket
import time

class Trading():
    def on_message(ws, message):
        print(message)
        time.sleep(4)

    def start(self):
        ws = websocket.WebSocketApp('wss://stream.binance.com:9443/stream?streams=btcusdt@trade', on_message=self.on_message)
        ws.run_forever(skip_utf8_validation=True)

if __name__ == '__main__':
    x = Trading
    x.start(x)
```

**Comment by engn33r** [comment]
First, some specific comments: You might need an API key to receive data at full speed. I tested the code you shared and get the same slow responses. You might have better luck using a project [built for the binance API](https://github.com/sammchardy/python-binance) instead of building one from scratch.

Now some general comments: If there is a way to split the websocket connection into multiple connections, you could [use multithreading](https://websocket-client.readthedocs.io/en/latest/threading.html) to compare performance. There are some minor websocket-client [performance improvements](https://github.com/websocket-client/websocket-client#performance) you can try. If performance is crucial for you, you can benchmark websocket-client against other websocket client implementations. If you have benchmarking data to share, it would be great to share here in case it shows areas for improvement.
