### ISSUE TITLE
New method add to handle just any callback error

### ISSUE THREAD

**Issue by hakancelikdev** [websocket-client/websocket-client#835]
How about adding a new method called `on_callback_error` to handle the errors that raise from any callbacks?

```python
def on_callback_error(self, ws, callback, exc) -> None:
        logger.debug(f"Exception raise on {callback.__name__}", exc_info=exc)
        self.close()

def _callback(self, callback, *args):
        if callback:
            try:
                callback(self, *args)
            except Exception as e:
                self.on_callback_error(self, callback, e)
```

https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L421

**Comment by engn33r** [comment]
I like this idea but I can see scenarios where `on_callback_error` is not implemented and then errors fail silently because logging is never called. Let me know if you have an idea how this could be resolved. I'll close this for now but will reopen if there is more interest or new ideas about this. There are several old issues in this project related to unclear callback messages (see #377) so an improvement would be nice.
