### ISSUE TITLE
WebSocketConnectionClosedException: Connection is already closed.

### ISSUE THREAD

**Issue by WisamAbbasi** [websocket-client/websocket-client#850]
I am trying to connect to the local host on port 3000 using below code:

    ws = websocket.WebSocketApp("ws://localhost:3000/ws",
                                on_open=on_open,
                                on_message=on_message,
                                on_error=on_error,
                                on_close=on_close)

    ws.run_forever()

But I keep get below error message:
WebSocketConnectionClosedException: Connection is already closed.

**Comment by engn33r** [comment]
Please see [the FAQ on this topic](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error).

**Comment by WisamAbbasi** [comment]
I do already use the function run_forever(), and I still do receive the error due to:

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by engn33r** [comment]
The problem is in the error message, the server does not accept your connection.

You could troubleshoot this by running some tests against [the echo-server.py file](https://github.com/websocket-client/websocket-client/blob/master/websocket/tests/echo-server.py) after starting it with `python3 websocket/tests/echo-server.py` and sending requests to it on port 8765. If the error exists with this server on port 8765, the issue is somewhere in your implementation code. If the server on 8765 works fine but the other server you try connecting to does not work, the issue is this other server.
