### ISSUE TITLE
Is it a good idea for run_forever to be executed in a separate thread?

### ISSUE THREAD

**Issue by NadavK** [websocket-client/websocket-client#856]
This is more of a call for advice, hope I am not abusing using the "issues".

```run_forever``` seems to hang my python app a little bit when losing connection to the server.
While this is to be expected, it has a negative impact my app.
I thought of running ```run_forever``` in its own thread.
Are there any pitfalls that would make this a bad idea?

**Comment by engn33r** [comment]
Which websocket-client version are you using? You can check using the output of `pip list`. Version 1.4.0 had a bug ([see changelog](https://github.com/websocket-client/websocket-client/blob/master/ChangeLog)) which should be fixed in version 1.4.1.

The hanging behavior you describe might be from [the `time.sleep` call](https://github.com/websocket-client/websocket-client/blob/3baacdafe246c4eb93b41850bb29bda7b73c5fc3/websocket/_app.py#L50) in the reconnect process. You can try a different sleep value to see if this improves the app.

The only pitfalls I know of are in [the threading docs](https://websocket-client.readthedocs.io/en/latest/threading.html), but some of the info there could be outdated. If you find inaccuracies in those docs, PRs are welcome.
