### ISSUE TITLE
websocket-client still in beta?

### ISSUE THREAD

**Issue by annatisch** [websocket-client/websocket-client#861]
Hello!
I see in your PyPI listing/setup.py - [the development status is listed as beta](https://github.com/websocket-client/websocket-client/blob/master/setup.py#L47), however the package version would indicate a stable release - so I just wanted to confirm whether this library was considered stable? And if so, is the package classifier likely to be updated?

Many thanks!

**Comment by engn33r** [comment]
I haven't seen an explicit definition for beta vs. stable for the PyPi development status. Most likely we could switch to stable right now, but since we're still working on a couple of bugs around `run_forever()` in the open issues, I'll leave as beta for now. I will switch it to stable if no new related issues crop up for a couple months after that is resolved.

**Comment by annatisch** [comment]
Thanks for clarifying @engn33r!
