### ISSUE TITLE
Automatic reconnect with dispatcher only happens when passing an interval to run_forever()

### ISSUE THREAD

**Issue by maynardflies** [websocket-client/websocket-client#863]
because of [this line](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L33), if a value for `reconnect` is not passed to `run_forever()`, the "interval" is set to 0 ([here](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L314)).  However, it is then later checked [here](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L433), and because 0 is falsy, this skips reconnecting and tears down the socket.  According to the current documentation, the socket should attempt to reconnect and doesn't mention requiring this to be passed.
 

Also note that `reconnect` is not in the documentation for `run_forever()`, so the only way to know about this is to read the code.

**Comment by bubbleboy14** [comment]
@maynardflies you're right, this is probably inconsistent with the docs. IIRC, the reconnect kwarg was introduced (initially with a default of 5) with version 1.4.0. But then, if I'm not mistaken, changing the default behavior of run_forever() caused some websocket-client -dependent projects to stop working right.

So in version 1.4.1, the reconnect kwarg's default was changed to 0, reverting run_forever() to pre-1.4.0 default behavior. If you prefer not to pass a reconnect value to run_forever(), you can change the default with the setReconnect() function.

So anyway, I agree that we should make sure the docs are consistent with the code's behavior. And ideally we should take care to avoid breaking existing integrations. What do you think, @maynardflies ? And what are your thoughts @engn33r ?

**Comment by maynardflies** [comment]
I think the simplest thing would be to change the docs to indicate that if
you want to have automatic reconnection, you must both pass a dispatcher,
AND pass the reconnect kwarg with a positive value.  If you want to keep
the docs the way they are, you could just assign the default (you mentioned
5) when run_forever is called with a dispatcher, and 0 otherwise.
Either way is fine, as long as the docs spell it out correctly, and the
pythondocs for the function should also list `reconnect` (it doesn't appear
at all right now) with the same consistent logic.

**Comment by bubbleboy14** [comment]
Yes, we should update the docs. IIRC, there may be some cases in which passing a dispatcher results in a slightly more stable (better at surviving spotty network conditions) connection.

However, use of an async dispatcher isn't exactly or chiefly related to reconnect behavior. The main difference is that by default websocket-client uses a synchronous dispatcher, so you can only run one WebSocketApp at a time unless you use (something like) threads. But if you pass in an async dispatcher like rel or pyevent, you can run as many WebSocketApps as you like in the same process. So that's the main distinction - other differences are incidental.

The reconnect kwarg is a relatively new addition to the project. Feel free to submit a PR with relevant updates to the docs :)

**Comment by psvaiter** [comment]
I forgot to mention, the version is pinned to `websocket-client==1.4.1`.

**Comment by engn33r** [comment]
I am mostly unavailable for the next 2 weeks but I gave this issue a read. I agree that the docs need an update so I will prepare a PR. Please add comments to the PR if I forgot something.

@psvaiter the behavior you observed sounds similar [to this report](https://github.com/websocket-client/websocket-client/pull/838#issuecomment-1228454826), and as explained it is currently expected that if the server disconnects gracefully `run_forever` does not automatically reconnect.
