### ISSUE TITLE
Suggestion: Add ability to send ping_payload with different opcode

### ISSUE THREAD

**Issue by bjebert** [websocket-client/websocket-client#882]
I've found the `run_forever` function to be extremely useful in handling sending periodic ping messages.  However, I'm faced with a websocket server which only responds to a specific ping payload sent with opcode=2.  It then returns its "pong" over opcode=2.  In my use case, I don't particularly care about receiving the pong, so have set ping_timeout=None.  However, I would appreciate the option to send ping_payload with opcode=2 rather than the default opcode=9. 

My alternative is writing async code to handle sending the ping with something like `ws.send(ping_payload, opcode=2)`, but the `run_forever` function suits me perfectly otherwise.

I appreciate this is a somewhat niche use case, so I understand if this functionality is deemed unnecessary or if it goes against best practices to implement.

**Comment by engn33r** [comment]
The behavior you are describing breaks the WebSocket specification. RFC6455 specifies [opcode 9 is for ping frames](https://datatracker.ietf.org/doc/html/draft-ietf-hybi-thewebsocketprotocol-13#section-11.8). Because this library intends to follow the specification, as described in the README, you will need to make a custom modification to your local version of the code.
