### ISSUE TITLE
web-socket client long-lived connection send AND  receive messages

### ISSUE THREAD

**Issue by Skill3t** [websocket-client/websocket-client#883]
**Describe the bug**
I want to create a web-socket client that connect so a server and listen to Incoming messages but also is able to send message so the same connection. If i use run_forever() i can receive messages but it is blocking so i can not send messages. When i use a dispatcher and do not use rel.dispatch() then i can send messages but not receive ones. 

**To Reproduce**
Code snippet to reproduce the behavior:

```
URL = "WSXXXX"
ws = websocket.WebSocketApp(URL,
        on_open=on_open,
        on_message=on_message,
        on_error=on_error,
        on_close=on_close
    )
ws.run_forever()

while True:
    ws.send('hallo')
    time.sleep(5)
```

So how can i use the nice on_message callback AND send message to the same web-socket?

**Environment:**
 - Python version: 3.10.6
 - Virtual Env: virtualenv,
 - OS: Ubuntu

**Comment by bubbleboy14** [comment]
Hello. Your first option is to send a message _inside_ your on_message callback.

If you're using rel, you can send (queue up) your messages _before_ running rel.dispatch().

The example you provided (send('hallo') every 5 seconds) can be achieved with rel.timeout, something like:

`
...

def hallo():
    ws.send('hallo')
    return True

rel.timeout(5, hallo)
ws.run_forever(dispatcher=rel)
rel.dispatch()
`

The basic idea is that (as you pointed out) you can't run anything "after" ws.run_forever() or rel.dispatch(), so your code needs to be structured somewhat asynchronously - your send()s need to be triggered by on_message(), a rel.timeout() -like timer mechanism, or some other event.

Does this design make sense for your use case? LMK if not.

**Comment by Bochelly** [comment]
Hello @bubbleboy14 
I just came across this discussion and was exploring what you suggested first.

`def on_message(ws, message):
    notification = json.loads(message)
    if notification["method"] != "Stream.OnUpdate":
        print(notification)
        **ws.send('Server.GetStatus')**`
        
 When doing something like that, I unfortunately don't get any response from the ws.send(), so it doesn't seem to be working in my case. Do you have any clue on what I might be doing wrong?

**Comment by bubbleboy14** [comment]
hey @Bochelly i made a test case for this. here's the server side, echo.py:

```
from dez.network.websocket import WebSocketDaemon

def regConn(conn):
        def echo(msg):
                print(msg)
                conn.write(msg)
        conn.set_cb(echo)

WebSocketDaemon('localhost', 4321, regConn).start()
```

here's the client, bidir.py:

```
import rel, websocket

def receiver(ws, msg):
    print("received:", msg)
    if msg.startswith("yo"):
        retort = "no" + msg
        print("retorting:", retort)
        ws.send(retort)

ws = websocket.WebSocketApp("ws://localhost:4321", on_message=receiver)

i = 0
def sender():
    global i
    i += 1
    msg = "yo %s"%(i,)
    print("sending:", msg)
    ws.send(msg)
    return True

rel.timeout(5, sender)

ws.run_forever(dispatcher=rel)
rel.dispatch()
```

so save those and then run:

`python3 echo.py`

and in another terminal run:

`python3 bidir.py`

this should test both cases. every 5 seconds, the client sends a message to the server, which echoes the message back.

the receiver() function (registered with WebSocketApp instance as on_message) prints the message, and, if it starts with 'yo', retorts with 'no' + msg. the server echoes that back, but the client _doesn't_ retort, because it doesn't start with 'yo'.

so at least with the rel dispatcher, both variants (send() in a timeout and send() in an on_message()) seem to work. and this example could be slightly altered to test the default (no dispatcher) mode.

does it work for you? if not, could you please provide a short (server/client) example?

**Comment by engn33r** [comment]
Due to lack of any response, I will assume this issue has been resolved.

Regarding the initial example, try using threading.Timer instead of sleep to create a delay, [as I mentioned here](https://github.com/websocket-client/websocket-client/issues/899#issuecomment-1584352485)
