### ISSUE TITLE
High CPU usage with skip_utf8_validation=False

### ISSUE THREAD

**Issue by wsdea** [websocket-client/websocket-client#921]
Hello, 

I'm using this script to listen to a websocket.

```python
import websocket, time

def on_message(ws, message):
    print('message received', time.time())
        
ws = websocket.WebSocketApp(
    "wss://ws.backpack.tf/events",
    on_message = on_message,
    header={
        'batch-test': 'true', 
    },
)
ws.run_forever(reconnect=60, ping_interval=50)
```

I receive 1 message every ~4 secs and messages are quite large. I noticed that my raspberry was reaching 100% CPU usage just by doing this.

After hours of research, I found that I needed to add `skip_utf8_validation=True` so that the CPU usage was normal (less than 5%).

Is this normal behaviour ? Thanks

**Comment by engn33r** [comment]
The reason the utf8 validation added a lot of overhead is because you are handling very large amounts of text very often on a low power device. The improvement of skipping utf8 validation is already captured in the [Performance section of the README](https://github.com/websocket-client/websocket-client#performance).
