### ISSUE TITLE
debug message 'Sending ping' polluting main logging that runs in debug mode

### ISSUE THREAD

**Issue by morchius** [websocket-client/websocket-client#940]
As mentioned above, using websocket-client framework to connect to websockets in a programme that itself is logging in debug mode. Therefore, the debug messages 'Sending ping' originating from _app.py is polluting my logs.

How can I tell my programme that the logging in the websocket-client is different to my logging in main.py ?

**Comment by morchius** [comment]
Yes sir, I have. I think there was a commit around 7 month ago
https://github.com/websocket-client/websocket-client/commit/8af1cbb17f5f12c9999fc56adf7b0187a1714174
This introduced the logging before there was not logging of sending ping if I see correctly

**Comment by engn33r** [comment]
As I understand it, you want websocket-client to work in debug mode but you don't want a certain debug message in your logs. Because you have a custom use case, you can create your own custom version of websocket-client or modify your logging approach to filter the logs. Unless I am misunderstanding the issue you describe, I do not consider the scenario you described as a problem with websocket-client.
