### ISSUE TITLE
Exceptions are "protected"

### ISSUE THREAD

**Issue by daveisfera** [websocket-client/websocket-client#960]
Currently, the exceptions are in `_exceptions.py` so linters warn about it being "protected"

Could this file be renamed or a "public" export of the exceptions be made available?

**Comment by engn33r** [comment]
Which linter are you using, and are you using default settings? When I run pylint with default settings, I get many warnings, so it would help to understand why specifically [W0212](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/protected-access.html) about protected access is a problem for you but not the other warnings.

Reducing linting errors is a good action item for future improvement, I added it to #684

**Comment by engn33r** [comment]
I fixed some lint errors in 75ba91a107852957437a9f4ef237fbd3d2b32214 but I did not find this lint error in the library code, only in the test files (but those are now fixed). Since the lint error is not found in the library code itself, I will close this issue.

I guess the issue that you are seeing is because you are using `import websocket as ws` and later using `ws._exceptions.WebSocketProtocolException`. If you change this to `from websocket._exceptions import WebSocketProtocolException`, then you can use `WebSocketProtocolException` directly and there is no message from pylint.

**Comment by daveisfera** [comment]
The problem is the import having `_` at the front. I'm already doing `from websocket._exceptions import WebSocketProtocolException` and that's what the PyCharm linter is warning about

**Comment by engn33r** [comment]
I'm not familiar with PyCharm as much as other linters. Can you recommend a solution that does not involve renaming the file? It would also help to understand why you only see this issue with _exceptions.py, because all the files in this library start with an underscore.

**Comment by daveisfera** [comment]
That's the only file I tried to import from. If I imported from another file with an `_` at the beginning of the filename then it would run into the same warning

**Comment by bubbleboy14** [comment]
@daveisfera the exceptions in _exceptions.py can all be imported directly from websocket, e.g.:

`from websocket import WebSocketProtocolException`

Am I misunderstanding the issue?
